### ISSUE TITLE
support btrfs for /

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#116]
I would really appreciate it if the raspberryPi kernel gets support to have a btrfs as root file system. Currently I need to compile my own kernel but keep the kernel as original as possible. The problem is that after a new kernel is installed my rPi doesn't boot. But when I just copy my 'older' kernel over I won't get the new upstream changes and fixes.

**Comment by edt-xx** [comment]
I would also love this.  Since the PI is so limited by IO latency I would like to perform tests to see if using btrfs with lzo compression makes things faster.  So I would require the btrfs and lzo modules to be built in.

**Comment by spacelama** [comment]
It does depend on EXPERIMENTAL.  But on the other hand, given how slow sdcards are at random writing, and given how few write cycles they have compared to "proper" SSD, the contiguous COW nature of BTRFS should extend the life of our pi filesystems substantially.  No need to default to a btrfs filesystem, but please compile it into the kernel as ext4 has been, so it can be used for the root filesystem.

(I'm guessing lvm wouldn't work either, because I can't see it in modules.builtin.  Either one would suffice - whichever is smaller.  LVM not so good, but at least we'd be able to have a minimal ext4 root, and everything else split out onto multiple logical volumes with btrfs)

**Comment by technion** [comment]
If your goal is to achieve something experimental, are happy to compile your own kernel, and are frustrated by updates breaking it, the solution is to do updates this way:
sudo SKIP_KERNEL=1 rpi-update (updates your firmware)
git pull (from your kernel source directory)
Compile and install as normal. It will retain your settings, and usually there are only a few changed files, meaning you can compile in a few minutes.

**Comment by edt-xx** [comment]
The experimental flag is pretty well meaningless.  Think it disapears in
.39.  Btrfs may not be as feature complete as ext4 but it is already more
feature rich.  Bottom line is that it works, does the job well and has a
good support community.

**Comment by ghost** [comment]
Any news on this issue or do you still think that btrfs is experimental stuff which needs to be avoided?

**Comment by popcornmix** [comment]
We build it as a module:
CONFIG_BTRFS_FS=m

So you are free to use it for non-root filesystems (e.g. create a btrfs partition that is mounted after the rootfs).

I'm not sure it's worth embedding in the kernel as few people will need it and the module size suggests it will consume significant memory:

```
-rw-rw-r-- 1 dc4 dc4 1042743 Sep  3 19:19 btrfs.ko
```

**Comment by P33M** [comment]
F2FS (flash-friendly-file-system) is preferable to btrfs. This is enabled by default on recent firmware.

```
CONFIG_F2FS_FS=y
CONFIG_F2FS_STAT_FS=y
CONFIG_F2FS_FS_XATTR=y
CONFIG_F2FS_FS_POSIX_ACL=y
```

**Comment by dsx724** [comment]
Can we reopen this issue? BTRFS is not very experimental anymore. F2FS is not the same thing. Compression alone is worth its weight in gold.

**Comment by dsx724** [comment]
Also F2FS in my experience has been far more unstable. The last version where I had an issue with BTRFS was kernel 3.16. F2FS is corruption prone for me to this day especially in emergency poweroff scenarios.

**Comment by lapineige** [comment]
Seconding this demand to reopen, it's a pain to setup right now while the filesystem has many advantages when using an external drive with a Raspberry Pi.

**Comment by SV-97** [comment]
Considering a reopen would be really nice. There's cases where ext isn't workable and the current way to get btrfs working is an absolute pain (I still couldn't get it to work) - especially for non-experts.

**Comment by XECDesign** [comment]
Why does it need to be re-opened? What's stopping people from using BTRFS right now?

I believe in Raspberry Oi OS Bookworm, you should be able to convert to BTRFS without any issues as long as you don't use kernel_2712.

**Comment by pelwell** [comment]
...because Bookworm releases now use initramfs automatically, and the btrfs module is included.

**Comment by SV-97** [comment]
Thanks! I was looking for how to get btrfs to work since bullseye and was roughly following some older guides for the rpi4 and just kept on trying things along that line with bookworm which must've messed something up because I always got kernel panics when trying to use a btrfs root.

In case someone else finds this thread when searching online: simply editing `/etc/fstab` and `/boot/cmdline.txt` for btrfs on a fresh image and running a `btrfs-convert` on the root partition appears to be working just fine (I also installed `btrfs-progs` prior to the convert which triggered a initramfs rebuild but that probably wouldn't be necessary)

EDIT: I eventually (after a few reboot cycles) ran into some problems due to swap which prevented a boot. For my case it was sufficient and acceptable to simply permanently disable swap using (from Feriman's answer on the raspberry pi SE post [How to permanently disable swap on Raspbian Stretch Lite](https://raspberrypi.stackexchange.com/questions/84390/how-to-permanently-disable-swap-on-raspbian-stretch-lite))
```bash
sudo dphys-swapfile swapoff
sudo dphys-swapfile uninstall
sudo update-rc.d dphys-swapfile remove
sudo apt purge dphys-swapfile -y
sudo sysctl -w vm.swappiness=0
```
I haven't run into any other issues since.

**Comment by XECDesign** [comment]
That was even more straight-forward than I expected. Thanks for testing and reporting back.
