### ISSUE TITLE
Serial Port sending one byte during opening

### ISSUE THREAD

**Issue by expeyes** [raspberrypi/linux#12]
I tried the serial port on Rpi to run expEYES and everything is working fine.  Whenever the '/dev/ttyAMA0' is opened , one byte (value = 0xF8) is send to the connected device. I just added a work around in the expEYES code on the uC. The code used for testing it is attached. The byte send is tracked on the uC end using a debugger.

Ajith
========================== code used =================================
# include <fcntl.h>
# include <termios.h>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <unistd.h>

int fd;

int main()
{
char ss[10];
char c;

  fd = open ("/dev/ttyAMA0", O_RDWR | O_NOCTTY);
  if (fd < 0)
        {
        fprintf(stderr,"ERROR opening AMA0\n");
        exit(0);
        }
return 0;
}

**Comment by nomis** [comment]
https://github.com/lp0/linux/commit/d5a48d1f54d2e736cdfa7d6e1602e69feb36c773 fixes this issue

**Comment by alepez** [comment]
Is this bug fixed? I can't find it https://github.com/raspberrypi/linux/blob/rpi-3.6.y/drivers/tty/serial/amba-pl011.c

**Comment by NewWorld** [comment]
This bug is still present.

`uname -a`: Linux danpi 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux

Code used to test (the issue is the same if I use the code in the OP):
`python -c 'import os; os.open("/dev/ttyAMA0", os.O_RDWR)'`

At baudrate 57600 and higher, on opening the serial port, the byte 0xFE is sent every time. At baudrate 9600 I can still see the spike on my oscilloscope but it's narrow enough that it doesn't count as a transmitted byte and it's not picked up on the RX.

@popcornmix  reverted the bugfix without explanation in a8b8699e504abf866fa3bfe06d64a38337d32cdb . I wonder why that was done.

**Comment by popcornmix** [comment]
There is a comment here: https://github.com/raspberrypi/linux/issues/148
That commit breaks the serial console. Continue suggestions in that (open) issue.

**Comment by popcornmix** [comment]
Patch has been merged and is in latest rpi-update firmware.
Can you test?
