### ISSUE TITLE
support VIDIOC_CROPCAP and VIDIOC_S_CROP in v4l2 kernel module for bcm2835

### ISSUE THREAD

**Issue by zoff99** [raspberrypi/linux#1776]
support VIDIOC_CROPCAP and VIDIOC_S_CROP
in the video4linux2 kernel module of the camera
https://github.com/raspberrypi/linux/tree/rpi-4.4.y/drivers/media/platform/bcm2835

to be able to just get a smaller region from the camera (and client apps can remain unchanged)

**Comment by popcornmix** [comment]
Ping @6by9

**Comment by zoff99** [comment]
https://kernel.org/doc/html/latest/media/uapi/v4l/vidioc-g-crop.html

**Comment by zoff99** [comment]
if i hardcode my wanted crop values here:
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/media/platform/bcm2835/bcm2835-camera.c#L1072
and compile the kernel module, will this actually crop? or is more needed?

**Comment by 6by9** [comment]
This has been kicking around for a while and I've just not had the chance to follow it through.
byterg on the forums had put together a patch (https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=62364&p=779385#p779385) which I had tidied up but never really tested.

I've pushed the change I've had locally for a while up onto my github repo (https://github.com/6by9/linux/, rpi-4.4.y branch), but it's likely to be incorrect. (There is also a second in progress change there that is unrelated but I couldn't be bothered to separate out. It should be innocuous but didn't work for RGB3/BGR3 formats due to an incorrect buffer size).
The weird bit is around what to do if the resolution gets changed and the values to set up with VIDIOC_CROPCAP https://kernel.org/doc/html/latest/media/uapi/v4l/vidioc-cropcap.html#c.v4l2_cropcap

I had a system up using QV4L2 the other day, so I'll try to resurrect the patches and work out what the correct answer is. It may be that we can fix the CROPCAP numbers at some arbitrary value (max resolution?) and then scale, but I don't know if that is the correct answer or not.
It needs to pass v4l-compliance too.

**Comment by 6by9** [comment]
Checking the crop API is deprecated in favour of the selection one, see https://kernel.org/doc/html/latest/media/uapi/v4l/crop.html vs https://kernel.org/doc/html/latest/media/uapi/v4l/selection-api.html
The guidance from the docs is
> Driver developers are encouraged to implement only selection API. The former cropping API would be simulated using the new one.

It does look like the V4L2 core does the right thing in mapping old API userspace to new API kernel driver (https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/media/v4l2-core/v4l2-ioctl.c#L2100), but means we actually want to understand and implement the new selection API.

**Comment by JamesH65** [comment]
@6by9 I suspect this can be closed....

**Comment by 6by9** [comment]
Please leave it open.
It should really be titled "support the V4L2 selection API" now due to the cropping API being deprecated.

**Comment by JamesH65** [comment]
Changed title...

**Comment by JamesH65** [comment]
ping @6by9

**Comment by 6by9** [comment]
No, no movement.

**Comment by ServeurpersoCom** [comment]
+1 digital zoom (crop) on robots is an awesome feature! help ?

**Comment by JamesFlosse** [comment]
+1 for "crop" function :).

**Comment by 6by9** [comment]
+1's only annoy.
I still haven't managed to get my head around the selection API and how it would apply to the Pi camera configuration. It'll happen when it happens.

**Comment by ServeurpersoCom** [comment]
How to support you? there is a way to donate?

**Comment by pelwell** [comment]
We are (mostly) all paid employees of Raspberry Pi, and if we aren't working on your issue that's because we are committed to other, higher priority tasks. The only real way to support us is to do the work (or pay somebody else to) and submit a pull request - it sounds like the cropping could be done in the kernel driver, although that might not be the most efficient implementation, so all the necessary information should be available.

**Comment by ServeurpersoCom** [comment]
Any news ?

**Comment by 6by9** [comment]
Closing as not planned. The legacy camera stack is deprecated, and cropping is supported by libcamera.
