### ISSUE TITLE
Problem updating clone of rpi linux repo

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/linux#1789]
I have been using a clone of the Linux repo for years now and usually have no problems updating it, however, trying to update today I have a real problem.

I update using git pull and normally I have no problems but today I got the following
```
Wed 11 Jan 22:02:34 GMT 2017
cd /home/pi/src/linux
git checkout rpi-4.4.y
Already on 'rpi-4.4.y'
Your branch is ahead of 'origin/rpi-4.4.y' by 5 commits.
  (use "git push" to publish your local commits)
git pull
remote: Counting objects: 65, done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 65 (delta 36), reused 1 (delta 1), pack-reused 0
Unpacking objects: 100% (65/65), done.
From https://github.com/raspberrypi/linux
   83f8ed3..a9fe228  rpi-4.4.y  -> origin/rpi-4.4.y
   a0d1d3e..905df9e  rpi-4.10.y -> origin/rpi-4.10.y
   ad9bae6..061dccc  rpi-4.8.y  -> origin/rpi-4.8.y
   456b547..7992701  rpi-4.9.y  -> origin/rpi-4.9.y
Auto-merging arch/arm/boot/dts/overlays/README
Auto-merging arch/arm/boot/dts/overlays/Makefile
error: Empty commit message.
Not committing merge; use 'git commit' to complete the merge.
```
I have never seen this behaviour before so I'm not really sure what is going on and why did I get this message `Your branch is ahead of 'origin/rpi-4.4.y' by 5 commits`. 

After the auto-merging lines the nano editor opened with the following message
```
Merge branch 'rpi-4.4.y' of https://github.com/raspberrypi/linux into rpi-4.4.y

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.
```
I did a brand new clone of the Linux repo and did a diff of the two clones and found my original clone had 4 files not included in the new diff and a number of differences to some files,

Can someone explain what is going on?

**Comment by pelwell** [comment]
I can. Unfortunately we broke one of our own rules and force-pushed the rpi-4.4.y branch in order to remove some rogue commits. The future branches - 4.8, 4.9, 4.10 - are regularly rebased and force-pushed to keep the Linux history clean, but once they become the branch from which mainline releases are made we stop that and use merges to pull in subsequent Linux changes.

If you find yourself in that situation, the first thing to do is to abort the current rebase - `git rebase --abort` - to allow you to assess the situation before making any changes. If you have local commits then you'll want to rebase them on top of the new upstream head, otherwise you can just hard-reset your local tracking branch to the upstream head.

For these examples, `rpi-4.4.y` is the branch tracking `origin/rpi-4.4.y`, and `dev` contains some local commits on top of `rpi-4.4.y`.

To rebase the `dev` branch onto the updated upstream branch:
```
git rebase --onto origin/rpi-4.4.y rpi-4.4.y dev
```
This translates to "take the commits between rpi-4.4.y and dev and rebase them on top of origin/rpi-4.4.y, updating dev to the new head".

To update the tracking branch:
```
git checkout rpi-4.4.y
git reset --hard origin/rpi-4.4.y
```
I hope this helps, and apologies for the inconvenience.

**Comment by pelwell** [comment]
It occurs to me that:
```
git checkout rpi-4.4.y
git reset --hard origin/rpi-4.4.y
```
can be replaced with:
```
git rebase --onto origin/rpi-4.4.y rpi-4.4.y rpi-4.4.y
```
which can be further simplified to:
```
git rebase --onto origin/rpi-4.4.y rpi-4.4.y
```
As well as being slightly shorter, this may be quicker since it skips the checkout of the old rpi-4.4.y branch.

**Comment by MrEngman** [comment]
Looks like I managed to sort things out using:

```
git checkout rpi-4.4.y
git reset --hard origin/rpi-4.4.y
```

Thanks for your help.

**Comment by Electron752** [comment]
@MrEngman 

If you have a solution, perhaps it would make sense to close the issue?

**Comment by popcornmix** [comment]
I'll close.
BTW @MrEngman if your script runs a ``git pull`` then you might consider using ``git pull --rebase``.
I believe that will always in cases where git pull would have worked, and will also work in cases like this.
