### ISSUE TITLE
qiv with xscreensaver

### ISSUE THREAD

**Issue by hako1** [raspberrypi/linux#181]
Raspbian, qiv 2.2.4, xscreensaver 5.15

using qiv with xscreensaver will blank the screen after displaying a few pictures.

qiv invoked by line in .xscreensaver: "Other Pics" qiv -strfiud 10 /home/pi/pictures/*
the pictures are in a sub-folder structure also containing other (non-picture) files

**Comment by licaon-kter** [comment]
Any logs? errors?

**Comment by hako1** [comment]
No error messages on screen, I did not look at logs.
When the same command line is invoked in a terminal, the problem does not happen. But with xscreensaver the screen blanks after about 30-40 sec (3-4 pics in my case). 
Setting xscreensaver to change after 2 min, using ripples and qiv alternating, the blanking happens everytime at qiv's slideshow.

**Comment by licaon-kter** [comment]
maybe try to set up a longer blanking interval with **xset** ( https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling )

**Comment by ghostwheel** [comment]
I also fought with this issue. I discovered that qiv and xli have the same problem, and that it doesn't have to do with slideshow mode - even if qiv or xli just put an image in the screensaver and then exit, the screen still blanks. It also didn't seem to have to do with screen blanking.
I installed xv and used it in xscreensaver, as described in the xscreensaver manpage, and that does the trick. I'm not totally happy with this since xv doesn't render as nicely as qiv (I think it is because my screen is 16bit, and xv renders in 24bit or some such)

**Comment by hako1** [comment]
@licaon-kter: As xscreensaver has its own settings, changing the blanking interval in xset has no effect.

@ghostwheel: I could not install xv by apt-get (does not seem to be in the repositories). Where did you find it? - or compiled by yourself?

**Comment by ghostwheel** [comment]
I compiled it myself. Was quite easy. Download from here: ftp://ftp.trilon.com/pub/xv/xv-3.10a.tar.gz
I could put the binary somewhere if needed.
I discovered that it is possible to have a 32bit framebuffer, in which case images look much nicer.
Just add
framebuffer_depth=32
framebuffer_ignore_alpha=1
to config.txt

An alternative is to compile chbg, which is available on debian, just not on raspbian. I had problems with the compilation, but I think that was just because I didn't go the debian way. So you can try to install chbg from source.

**Comment by hako1** [comment]
While looking at qiv, I could not find the problem, probably comes with imlib2.

@ghostwheel:
I tried xv, but no success.
Unfortunately, my SD card got corrupted while accessing the PI via Samba. Had to re-install, took some time.
Can you put the binary somewhere, or even better, publish a deb so that others also can use it?
Alternatively, please tell how you compiled xv. I have problems with the jpg part. Maybe, you can post the makefile.

**Comment by ghostwheel** [comment]
Here is the xv dir after compilation finished:
https://www.dropbox.com/l/RWroOvAnHBxSvqtJ

**Comment by hako1** [comment]
Thank you! xv works.

**Comment by duncangallimore** [comment]
ghostwheel,
Sorry if this is a repeated post - it created two initially and I deleted one but now there are none!
I am having difficulty making xv on my RPi. Could you send me the binary?
Many thanks, Duncan

**Comment by ghostwheel** [comment]
Sure, I'll send it tonight when I get home.

## 

Michael Lachmann, Max Planck Institute for Evolutionary Anthropology
Deutscher Platz 6, 04103 Leipzig, Germany.

**Comment by duncangallimore** [comment]
Have you had chance? Sorry to hassle you.
Thanks, Duncan

**Comment by ghostwheel** [comment]
Sorry, I didn't get to it. Here it is.
I attached two archives: one contains the xv source dir after I finished
compiling xv, the other contains the xv binary, and all libs that it seems
to be using as I saw from 'ldd xv'.
If you're lucky, you can just copy the xv binary to /usr/local/bin, and all
should work. Or you can go to the source dir and do
make install
If those two don't work, then you can play with the libs (xv/lib)
somewhere. But I hope it doesn't get to that....

https://www.dropbox.com/s/obzkx7ekxmpam4c/xv_n_lib.tgz
https://www.dropbox.com/s/kai1eezo49dh6h9/xv_compiled.tgz

enjoy!
Michael

## 

Michael Lachmann, Max Planck Institute for Evolutionary Anthropology
Deutscher Platz 6, 04103 Leipzig, Germany.

**Comment by duncangallimore** [comment]
Thank you - will try later.

Duncan
