### ISSUE TITLE
VCDBG: Weird dependency on bcm2708_fb

### ISSUE THREAD

**Issue by Electron752** [raspberrypi/linux#1822]
So I found out the hard way that vcdbg has a dependency on the bcm2708_fb dma memcpy ioctl.  I was able to get vcdbg to work in 64 bit by adding a compatibility ioctl.

Anyway, I was wondering what the purpose of this weird dependency is? Can't vcdbg get all the information it needs from vc_mem?

**Comment by pelwell** [comment]
There are three reasons for using the bcm2708_fb memcpy:

1. It uses a special channel of the DMA controller which is cache-coherent with the VPU.
2. It has access to the top 16MB of RAM which is otherwise inaccessible to the ARM complex. Previously this RAM was unused, but thanks to this DMA channel we can let the VPU use it.
3. bcm2708_fb gets a performance boost from using DMA for blitting. The standard Linux DMA API doesn't recognise memory-to-memory as a possibility, hence the need to use a private API.
