### ISSUE TITLE
Latest kernel with smsc95xx error while headless

### ISSUE THREAD

**Issue by x-magic** [raspberrypi/linux#183]
```
$ uname -a
Linux BHGsRP-RPiRBL 3.6.11+ #348 PREEMPT Tue Jan 1 16:33:22 GMT 2013 armv6l GNU/Linux

$ /opt/vc/bin/vcgencmd version
Jan  2 2013 23:38:28 
Copyright (c) 2012 Broadcom
version 360331 (release)
```

Just like issue #149 and #60 when smsc9512 counter a heavy load on usb hub it will show a register read error, with eth0 link down sometimes. But I just spotted some new errors and never happened before I updated to the latest firmware: 

```
Jan  4 02:04:04 raspberrypi kernel: [20535.897405] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan  4 02:04:04 raspberrypi kernel: [20535.897439] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan  4 02:04:04 raspberrypi kernel: [20535.897455] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jan  4 03:26:00 raspberrypi kernel: [25451.696037] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan  4 03:26:00 raspberrypi kernel: [25451.696147] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan  4 03:26:00 raspberrypi kernel: [25451.696172] smsc95xx 1-1.1:1.0: eth0: Timed out reading MII reg 01
Jan  4 04:22:41 raspberrypi kernel: [28853.374164] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan  4 04:22:41 raspberrypi kernel: [28853.374198] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan  4 04:22:41 raspberrypi kernel: [28853.374214] smsc95xx 1-1.1:1.0: eth0: Timed out reading MII reg 01
```

Those "MII" related errors are never seen before. 

I have my 512MB rev2 Pi powered by GPIO 5V along with a portable harddrive on a 5V 2A adapter(the one come with Nexus 7) with a handmade cable that VCC and GND are connected to Pi and HDD only, while only D+ and D- of HDD is connected to Pi's USB. No another hub is used. No sign shows lack of power from the adapter to both Pi and HDD. 

I also tried to power the HDD and Pi separately (5V 1A on Pi's microUSB and 5V 1A on HDD) to run headless and similar errors are found in kernel log. 

I did a lot of search through web and it seems whether people didn't focus on this error or their Pi just not show these errors again, magically ;P

Should I worry about?

**Comment by davebiffuk** [comment]
I'm also seeing the ethernet drop out after some hours of uptime (typically 24 hours, but it varies).

This is on an original (256MB) model B running latest Raspbian, with only a single USB webcam attached directly to the USB port, it's a 046d:0817 Logitech, Inc. There are also a few 1-wire temperature sensors and a 16x2 LCD display attached to the GPIO lines. The whole lot is powered from the RS-supplied power supply.

I've seen this with kernel #350 and earlier kernels, I've since updated to #354 just a few minutes ago to see if that helps.

Please let me know if there's anything else I can do to help debug this. Thanks!

This is the kernel.log, immediately after the ethernet drops:

Jan 11 17:45:07 raspberrypi kernel: [278472.243617] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 11 17:45:07 raspberrypi kernel: [278472.243663] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 11 17:45:07 raspberrypi kernel: [278472.243682] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jan 11 17:45:12 raspberrypi kernel: [278477.243695] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 11 17:45:12 raspberrypi kernel: [278477.243726] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 11 17:45:12 raspberrypi kernel: [278477.243742] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jan 11 17:45:19 raspberrypi kernel: [278483.343793] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 11 17:45:19 raspberrypi kernel: [278483.343824] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 11 17:45:19 raspberrypi kernel: [278483.343841] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jan 11 17:45:24 raspberrypi kernel: [278488.343865] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 11 17:45:24 raspberrypi kernel: [278488.343896] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 11 17:45:24 raspberrypi kernel: [278488.343913] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jan 11 17:45:29 raspberrypi kernel: [278493.644019] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Jan 11 17:45:29 raspberrypi kernel: [278493.644068] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG
Jan 11 17:45:35 raspberrypi kernel: [278499.644109] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Jan 11 17:45:35 raspberrypi kernel: [278499.644156] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG

**Comment by popcornmix** [comment]
Can you update (rpi-update).
This commit may fix your problem:
https://github.com/raspberrypi/linux/commit/0d4c64977ac8baceeaf979921fbdcff1aa84e204

**Comment by davebiffuk** [comment]
Thanks. I did update yesterday, about 1pm, to kernel #354.

Just now I see these lines in kern.log, but the ethernet has stayed up, which is hopeful. I'll leave it alone to see if there are further "developments".

```
Jan 15 08:59:07 raspberrypi kernel: [70833.531203] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 15 08:59:07 raspberrypi kernel: [70833.531237] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 15 08:59:07 raspberrypi kernel: [70833.531254] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
```

**Comment by x-magic** [comment]
An update. I updated to #354 and no issue until now. It's up for over 120000 seconds. 

But there's no particular huge traffic over USB. My RPi is a headless download and samba server so I'm not sure if the error mentioned before would come again, but I will keep eye on that.

**Comment by davebiffuk** [comment]
Sorry to report kernel #354 still has this problem. Despite my [earlier comment](https://github.com/raspberrypi/linux/issues/183#issuecomment-12258997), after about 25 hours uptime, these lines appeared in kern.log, and the ethernet dropped. I've done rpi-update again, so now I'm running on #358. Anything else I try to help debug this? Ta.

```
Jan 15 14:12:07 raspberrypi kernel: [89613.758463] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jan 15 14:12:07 raspberrypi kernel: [89613.758497] smsc95xx 1-1.1:1.0: eth0: Error reading MII_ACCESS
Jan 15 14:12:07 raspberrypi kernel: [89613.758513] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
(above 3 lines repeated 3 more times, every 5 seconds, then...)
Jan 15 14:12:28 raspberrypi kernel: [89635.068707] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Jan 15 14:12:28 raspberrypi kernel: [89635.068754] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG
(above 2 lines repeated every 6 seconds)
```

**Comment by davebiffuk** [comment]
Ethernet dropped again with #358. Same pattern of messages in /var/log/kern.log as in my previous comment. Uptime was about 71.5 hours. The workload is USB traffic once/minute from the webcam, misc GPIO every 5 minutes for the temperature sensors, and very light Apache load, <100 requests/day.

I've now booted the Pi with
    smsc95xx.turbo_mode=N
which is the only other suggestion I've found that might help.

I'm happy to try possible solutions to debug this - just let me know. :-)

**Comment by P33M** [comment]
davebiffuk: What is your usage case? I.e. are you using the HDD for frequent/sporadic accesses or file server duties?

Can you both post "lsusb -t" and "lsusb" as well.

**Comment by x-magic** [comment]
It seems when smsc95xx.turbo_mode=N is used to boot up, problem's gone with latest kernel. I am using this option all the time and forget to mention it in my post. Sorry for that.

Well I don't need extra boost on USB performance to run a headless server (USB2.0 is much faster than 100BASE-T ethernet, as you see, NIC is the bottle neck)so I am pretty satisfied with the current kernel. Anyway, my pi is up for several days without related errors except an accidental memory overflow(I still don't get it why swap is now helping when some programs eat up all physical memory).

**Comment by davebiffuk** [comment]
P33M: in my case there's no HDD, only the SD card. No fileserver duties - the most frequent SD card access is due to capturing an image once a minute from the web cam. After that there's RRD updates every 5 minutes from the temperature sensors.

Here's the lsusb output. There's only one webcam connected - I don't know why it shows up twice in the "-t" output.

```
pi@raspberrypi ~ $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=hub, Driver=hub/3p, 480M
        |__ Port 1: Dev 3, If 0, Class=vend., Driver=smsc95xx, 480M
        |__ Port 3: Dev 4, If 0, Class='bInterfaceClass 0x0e not yet handled', Driver=uvcvideo, 480M
        |__ Port 3: Dev 4, If 1, Class='bInterfaceClass 0x0e not yet handled', Driver=uvcvideo, 480M
pi@raspberrypi ~ $ lsusb
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 046d:0817 Logitech, Inc.
pi@raspberrypi ~ $
```

Uptime with smsc95xx.turbo_mode=N is 57 hours and counting...

**Comment by davebiffuk** [comment]
Sorry to report that running with smsc95xx.turbo_mode=N I got the same ethernet drop after ~84 hours uptime, with the same messages in kern.log.

I've rebooted without that now FWIW. I'm going to write a script to reboot the Pi if the ethernet's down and those errors are present in kern.log - it's a gross hack though :-(

**Comment by mupett** [comment]
Same problem here ... :(

**Comment by stuartyio** [comment]
I'm experiencing the same. Prolific PL2303 USB to serial adapter plugged in. Ethernet goes down every few days.

**Comment by mupett** [comment]
davebiffuk can you please post the script to reboot when eth0 goes down? Kind regards :)

**Comment by davebiffuk** [comment]
Funny thing is, having rpi-update'd before the last reboot (to kernel #362, firmware 364243) my Pi's ethernet has been up for 156+ hours now. The firmware commit message "Bump to latest firmware LKG65" doesn't give any clues as to what's been changed though.

I'm still seeing occasional bursts of "Failed to read register index 0x00000114" etc. But the network is not dropping. (Hope I don't jinx it by posting this...)

Therefore my reboot-on-dropped-network is completely untested :-) but help yourself: some modification will be necessary, run it from cron every 5 minutes (say). https://docs.google.com/file/d/0BwU_0Q35xHhGUi1iYzdoWl9TNWs/edit?pli=1

**Comment by mupett** [comment]
thanks a lot dave

**Comment by davebiffuk** [comment]
Regret to report that after 13.5 days uptime (325 hours) on kernel #362/firmware 364243, the problem recurred. Ethernet dropped while Pi continued running. (Irritatingly my script to reboot the Pi didn't kick in; the perils of debugging odd scripts like that...)

Now rpi-update'd to kernel#368/firmware 366977 and keeping an eye on it.

**Comment by stuartyio** [comment]
I've also updated to kernel#368/firmware 366977 this morning.  I'll report if Ethernet drops out.

pi@raspberrypi ~ $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=hub, Driver=hub/3p, 480M
        |__ Port 1: Dev 3, If 0, Class=vend., Driver=smsc95xx, 480M
        |__ Port 3: Dev 4, If 0, Class=vend., Driver=pl2303, 12M
pi@raspberrypi ~ $ lsusb
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

**Comment by ghost** [comment]
Reporting that my Pi (kernel#339/firmware 379325) drops the USB after only a few seconds when booted. Will check voltage when I can get my hands on a multimeter, but as the errors are exactly the same and it has run before without any problem for over a week without rebooting, I don't suspect my PSU.

Update:
My Pi just recovered. It has been running for a few days now without any crashes. The only thing that has changed is that I moved my router. The wire between the modem and the router was faulty and I've moved it next to my computer instead of under a dusty table in the living room. As an effect, the Pi is now directly connected to the router while first it was through a switch.
I'll keep monitoring it, but there are no signs of impeding doom.

**Comment by ghollingworth** [comment]
Assuming the issue is now closed please reopen if you still see this.

**Comment by azbesthu** [comment]
Hi,

I got HW_CFG_LRST_ and MII_ACCESS failures after a half minute when I start using the attached Alcor micro AU9540 (058F:9540) smartcard reader. The network is slows down to zero. The same failure occures with direct  raspi - card reader and raspi -external hub - card reader setup. Same results with rev1 (0002) powerd from thinkpad usb and  rev2 (000f) Pi back powerd from active hub. 

Here is some log: https://gist.github.com/azbesthu/7116016

I had to add dwc_otg.speed=1 to cmdline.txt. This seems to resolve the network outage, but 12Mbps usb speed is not enought for usb dvb-t reception and network streeming. 

I tried with raspi-update the 3.6.11 #557 kernel with same results. With the previously raspbian and raspbmc it worked fine.

**Comment by ckamas** [comment]
I am seeing this issue on 4.9.76-rt60-v7+ running on a RPI CM3. Has this issue been resolved, or is it back again? If it is solved, please point me to the correct patch.

[ 3614.344611] smsc95xx 1-1.1:1.0 eth0: Failed to read reg index 0x00000114: -110
[ 3614.344620] smsc95xx 1-1.1:1.0 eth0: Error reading MII_ACCESS
[ 3614.344626] smsc95xx 1-1.1:1.0 eth0: MII is busy in smsc95xx_mdio_read
[ 3614.344632] smsc95xx 1-1.1:1.0 eth0: Failed to read MII_BMSR


[43053.607537] smsc95xx 1-1.5.1:1.0 eth1: Failed to read reg index 0x00000114: -110
[43053.607547] smsc95xx 1-1.5.1:1.0 eth1: Error reading MII_ACCESS
[43053.607553] smsc95xx 1-1.5.1:1.0 eth1: MII is busy in smsc95xx_mdio_read
[43053.607559] smsc95xx 1-1.5.1:1.0 eth1: Failed to read MII_BMSR

**Comment by pelwell** [comment]
Please don't resurrect long-closed threads.

**Comment by karimcitoh** [comment]
> I am seeing this issue on 4.9.76-rt60-v7+ running on a RPI CM3. Has this issue been resolved, or is it back again? If it is solved, please point me to the correct patch.
> 
> [ 3614.344611] smsc95xx 1-1.1:1.0 eth0: Failed to read reg index 0x00000114: -110
> [ 3614.344620] smsc95xx 1-1.1:1.0 eth0: Error reading MII_ACCESS
> [ 3614.344626] smsc95xx 1-1.1:1.0 eth0: MII is busy in smsc95xx_mdio_read
> [ 3614.344632] smsc95xx 1-1.1:1.0 eth0: Failed to read MII_BMSR
> 
> [43053.607537] smsc95xx 1-1.5.1:1.0 eth1: Failed to read reg index 0x00000114: -110
> [43053.607547] smsc95xx 1-1.5.1:1.0 eth1: Error reading MII_ACCESS
> [43053.607553] smsc95xx 1-1.5.1:1.0 eth1: MII is busy in smsc95xx_mdio_read
> [43053.607559] smsc95xx 1-1.5.1:1.0 eth1: Failed to read MII_BMSR

Same problem here. @ckamas did you open an issue for this one?

**Comment by ckamas** [comment]
I was able to solve this issue for me by compiling my own kernel in 
Yacto. The kernel provided by Kunbus had real time extensions enabled. I 
believe that this MIGHT be the issue. Unfortunately the engineer 
assigned to follow up on this with the community has left the 
organization, and I do not have any more bandwidth to follow up on my 
theory myself.
