### ISSUE TITLE
Can't read ID EEPROM on Pi Zero W

### ISSUE THREAD

**Issue by Naegolus** [raspberrypi/linux#2130]
Hi,

the following works on Pi 2 and Pi Zero but not on the Pi Zero W:
root@raspberrypi:/sys/class/i2c-adapter/i2c-0/0-0050# hd eeprom
hd: eeprom: Connection timed out

Using kernel version:
root@raspberrypi:/sys/class/i2c-adapter/i2c-0/0-0050# uname -a
Linux raspberrypi 4.9.39+ #1020 Sat Jul 22 14:08:01 BST 2017 armv6l GNU/Linux

I'm using this kernel version, because I modified the at24 driver a bit.
What did I do:
1. Downloaded a vanilla Raspbian
2. Added "dtparam=i2c_vc=on" to config.txt. After that I had the directory "/sys/class/i2c-adapter/i2c-0"
3. Executed: "echo "24c32 0x50" > new_device" in directory "i2c-0". Then the directory "0-0050" was created, but there was no "eeprom" file in there.

I saw in the at24 driver, that following code was added, somewhere between 4.4.y and 4.9.y:
	/*
	 * Perform a one-byte test read to verify that the
	 * chip is functional.
	 */
	err = at24_read(at24, 0, &test_byte, 1);
	if (err) {
		err = -ENODEV;
		goto err_clients;
	}

The driver tries to read one byte from the EEPROM in function at24_probe(). If no chip is present, the probing fails.
In our case we don't have the chip connected on startup (because we use the Pi as test equipment, the chip is connected via pogo test pins). I commented out this code and the eeprom file showed up.

Now. Using this SD card. The "hd" command works on the Pi 2 and Pi Zero but not on the Pi Zero W.
I think the only difference left should be the loaded device tree file ..

Can anyone reproduce this?

**Comment by pelwell** [comment]
We don't recommend using I2C0 (i2c_vc) because it isn't guaranteed to be safe on all platforms. The eepflash shell script we provide for HAT developers uses a software I2C implementation instead:
```
sudo dtoverlay i2c-gpio i2c_gpio_sda=0 i2c_gpio_scl=1
```
This creates /dev/i2c-3 on GPIOs 0 and 1.

Having said that, in the Pi Zero W case there's actually no reason why it shouldn't be OK - it's just that the in-built dt-blob that the firmware uses to configure the pins is leaving the I2C0 alt-function enabled on GPIOs 28 & 29 at the same time as you are trying to use it on GPIOs 0 & 1 (mapping an I2C interface to multiple pin groups breaks it).

All camera-capable platforms used to statically enable I2C0 on 28&29, but then the firmware was changed to enable it as needed, allowing the same I2C interface to be multiplexed between several pin groups. At the same time, the static mapping was removed, but because of parallel development in a side branch the Zero W pin settings were missed, leading to the problem you see now.

I've tested with a modified dt-blob on a Zero W and /dev/i2c0 works as expected. The fixed dt-blob will appear in a future firmware release, but until then you have a few options:
a) Use `i2c-gpio` as show above.
b) Run the following after booting:
```
raspi-gpio set 28 ip
raspi-gpio set 29 ip
```
c) Download a replacement dt-blob.bin from [here](https://drive.google.com/file/d/0B_P-i4u-SLBXT3h6OE1CNXA0STA/view?usp=sharing), copy it into the boot partition (/boot) and reboot.
This external dt-blob will be used in preference to the internal one, so by installing it you will masking any future updates to the built-in version.

I'll add a comment here when a new firmware is released, at which point you can update and remove your workaround.

**Comment by Naegolus** [comment]
Wow. Thank you for the explanation!

Tested the modified blob => Working
