### ISSUE TITLE
Error: loading kdump-tools on RPI3-B rev1. Kernel Linux raspberrypi 4.9.51-v7+ 

### ISSUE THREAD

**Issue by yogender09** [raspberrypi/linux#2211]
root@raspberrypi:/home/pi# sudo apt-get install kdump-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kdump-tools is already the newest version (1:1.6.1-1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up kdump-tools (1:1.6.1-1) ...
dpkg: error processing package kdump-tools (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 kdump-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by popcornmix** [comment]
This github repo is used for reporting bugs in the linux kernel.

If your problem occurs on a clean install of raspbian stretch then you should report the issue here: https://github.com/RPi-Distro/repo

If it is occurring after your local apt repo has got in a bad state then the [forum](https://www.raspberrypi.org/forums) may be a better place for advice.
