### ISSUE TITLE
lightdm locales/kbd

### ISSUE THREAD

**Issue by moserwi** [raspberrypi/linux#2301]
findings:
lightdm-gtk-greeter-settings is not used by lightdm. even with update-alternatives --config lightdm-greeter
implementing a taskbar in lightdm is not possible, the used variables have been changed with prefix gtk-*

the locales/kbd system/session are not synced

errors:
installed debians lightdm  - taskbar and it uses the lightdm-gtk-greeter.conf
kbd is ok but lang selection without any function
So I assume that you altered the manipulation of locales and keyboard to fit the raspi-config.
BUT: uder these circumstances I'am not able to implement a lang and keyboard chooser at login and
therefore internatioalization is not really possible.

I am sure you are aware of the problem and you arer working on it.
Q: can you give me the timeframe when you solve the lang/kbd selection and the sync problem?

tks
willi

**Comment by pelwell** [comment]
This repo is for the RPi Linux kernel, and your issue isn't a kernel problem.

@spl237 This is deep in your territory - where, if anywhere, should willi report this?

**Comment by spl237** [comment]
We do not use the lightdm-gtk-greeter any more; we have a cut-down greeter called pi-greeter. It does not offer any of the taskbar or internationalisation features, as they clutter the display and are not fundamentally necessary to enable a user name and password to be entered.

If you wish to restore the original greeter functionality, update /etc/lightdm/lightdm.conf and change the "greeter-session" line to "lightdm-gtk-greeter" instead of "pi-greeter". Any issues with lightdm-gtk-greeter should be reported upstream to the Debian or LightDM maintainers, as we have not changed its code at all.

**Comment by moserwi** [comment]
Thank you for info.

brgds willi
