### ISSUE TITLE
Pi Configuration Locale Missing

### ISSUE THREAD

**Issue by ptdesign** [raspberrypi/linux#2445]
Set Locale Language pt (Portugal Portuguese) is missing since last versions of raspberry pi.

**Comment by pelwell** [comment]
While looking at a similar issue we've spotted a problem with sub-languages (like Austrian German and Braziliian Portuguese). The app was displaying the name of the first (alphabetically) language in the list with the same major language - so de -> de_at, pt -> pt_br. However, the problem is confined to the displayed name of the locale - the correct locale is actually selected.

The fixed app requires some testing and packaging, but it should be available in a week or so.

**Comment by ptdesign** [comment]
@pelwell good to know you reviewed this. And don't forget the pt -> pt_pt

**Comment by pelwell** [comment]
I'm assured that is also fixed.

**Comment by ptdesign** [comment]
@pelwell New release from 2018-04-18 doesn't provide info about this fix.

**Comment by pelwell** [comment]
The "bug" wasn't in the kernel or firmware, so it wouldn't be mentioned here or in the firmware repo.

**Comment by pelwell** [comment]
This is the specific GUI commit that fixed it: https://github.com/raspberrypi-ui/rc_gui/commit/3e6fc4a27e6cf7c0655140d6e239055e27325857

**Comment by ptdesign** [comment]
Ok. Thanks

**Comment by pelwell** [comment]
> Ok, but is included in last release? Thanks

[ Finds spare card ]
[ Installs image ]
[ Tests localisation ]

Yes.

**Comment by JamesH65** [comment]
@ptdesign OK to close this?

**Comment by ptdesign** [comment]
Ok, thanks for heads up!
