### ISSUE TITLE
Revert "bcm2835-i2s: get base address for DMA from devicetree" 

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2451]
I'm having some issues with I2S, and I saw this issue : 
https://github.com/raspberrypi/linux/issues/1271

My issue : 
bcm2835-i2s 3f203000.i2s: I2S SYNC error!
bcm2835-dma 3f007000.dma: DMA transfer could not be terminated

Codec is master in both clocks. 

For 4.9, do wee need to revert :
"bcm2835-i2s: get base address for DMA from devicetree"  ? 

Thanks

**Comment by HiassofT** [comment]
You can ignore the I2S SYNC error, this always happens if bcm2835-i2s is slave.

"DMA transfer could not be terminated" will show up if the codec, which is clock master, didn't drive the clock lines. Look into that, either the codec isn't setup properly or the clock lines aren't connected correctly.
