### ISSUE TITLE
boot_id does not change

### ISSUE THREAD

**Issue by GoTeamAnt** [raspberrypi/linux#2476]
On a pi0 without RTC /proc/sys/kernel/random/boot_id does not change between boots.

This trips up journald which leads to a corrupted journal.

**Comment by GoTeamAnt** [comment]
I am on archlinux with kernel 4.14.30

**Comment by pelwell** [comment]
How strange - it seems to be broken on 4.14 for Pi0 and Pi1.

**Comment by pelwell** [comment]
For a while this seemed to have turned into a Heisenbug, but actually the result is just timing dependent.

It looks like the 4.14 kernel on Pi 1 has insufficient entropy at the point the boot_id is generated to create a unique value. I haven't recorded all of the contributing values but it's possible that the timing of an interrupt is the only variation. I have yet to work out what changed since 4.9 to make it worse.

**Comment by GoTeamAnt** [comment]
Today I upgraded to 4.14.39 and the issue seems to be fixed.

I rebooted 8 times and i got a different boot_id every time.

arch linux source:
_commit=865ddc1393f558198e7e7ce70928ff2e49c4f7f6
https://github.com/raspberrypi/linux/archive/${_commit}.tar.gz

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
