### ISSUE TITLE
Set CONFIG_BCM2835_DEVGPIOMEM=y for bcmrpi3_defconfig (aarch64)

### ISSUE THREAD

**Issue by ava1ar** [raspberrypi/linux#2514]
Hi!

I am using aarch64 kernel with my Raspberry Pi 3 and just discovered, that I can't use GPIO functionliaty without root on aarch64 kernel. Reason is /dev/gpiomem is not available, due to not enabled CONFIG_BCM2835_DEVGPIOMEM. However it is enabled for armv7 config. Any particular reason, why this is not enabled for aarch64? Can we have it enabled to enjoy the full GPIO functionality on aarch64?

**Comment by pelwell** [comment]
It's not enable by default because the people who contributed to bcmrpi3_defconfig didn't include it. This defconfig is a community effort - as I'm sure you know we aren't officially supporting aarch64 builds, but we do host the files necessary to build a 64-bit kernel and respond to simple requests like this.

The option has been added to the defconfig and it builds OK. I haven't tested it works as expected, but there's no reason why it shouldn't.

**Comment by ava1ar** [comment]
Thanks for the quick turnaround, pelwell! To confirm - I just got new kernel build and it works as expected. Closing the issue.
