### ISSUE TITLE
ALSA boot messages

### ISSUE THREAD

**Issue by licaon-kter** [raspberrypi/linux#282]
Any reason to output "bcm2835 ALSA chip created!" for each of those 8 subdevices?
On that note, why are there 8 anyway?

> **pi@raspberrypi:~/ > aplay -l**
> ***\* List of PLAYBACK Hardware Devices ****
> card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
>  Subdevices: 8/8
>  Subdevice #0: subdevice #0
>  Subdevice #1: subdevice #1
>  Subdevice #2: subdevice #2
>  Subdevice #3: subdevice #3
>  Subdevice #4: subdevice #4
>  Subdevice #5: subdevice #5
>  Subdevice #6: subdevice #6
>  Subdevice #7: subdevice #7

**Comment by popcornmix** [comment]
Having more than one alsa device means that if more than one sound is played, then the mixing gets done on GPU side, so reduces ARM CPU.

I can remove the boot messages. (Probably have to remove them all as they are created independently).

**Comment by martinezjavier** [comment]
popcornmix,

I wrote [this patch](https://github.com/martinezjavier/linux-rpi/commit/31e3bcd1936bef02f1d39e4dffa09e0519943367) that uses the audio_info() macro instead of printk() so these messages will be only shown when debug is enabled on the driver.

Is that what you had in mind? I will include that patch on the pull request to add mmap support for the driver.

Best regards

**Comment by popcornmix** [comment]
@martinezjavier 
Looks fine. Include it in your PR (as a separate commit).
