### ISSUE TITLE
Please review GPIO label changes

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/linux#2820]
Hi,
i prepared a patch series for the upcoming Linux Kernel 5.1 (upstream) to add the missing labels for GPIO in DTS. This is helpful for distributions with CONFIG_GPIO_SYSFS disabled or ARM64.

Here are the relevant changes:
https://marc.info/?l=linux-arm-kernel&m=154729717414105
https://marc.info/?l=linux-arm-kernel&m=154729716614104
https://marc.info/?l=linux-arm-kernel&m=154729707714068
https://marc.info/?l=linux-arm-kernel&m=154729713714098

It would be nice to get a review or feedback.

**Comment by lategoodbye** [comment]
@pelwell ping ...

**Comment by pelwell** [comment]
These patches were applied shortly you created this issue, so it's a bit moot, but if you really want feedback...

I have a problem with the whole idea of giving names to GPIOs that:
a. use pinctrl functions (i.e. they are not GPIOs) such as the SPI pins,
b. has the device driving that pin function disabled (SPI again), and
c. are effectively application-dependent.

In my opinion, GPIOs 2-27 should be called GPIO2-GPIO27.

1. https://marc.info/?l=linux-arm-kernel&m=154729717414105
```
According to the schematics for all RPis with a 40 pin header,
the GPIOs 0 and 1 are labeled as ID_SD and ID_SC. In order to
clarify that is a I2C bus, append the third letter.
```
Two 'l's in labelled, and I think you want 'that it is an I2C bus'. There's no question about the function of the pins, just the naming, and the _SCL and _SDA variants could be considered more recognisable.

2. https://marc.info/?l=linux-arm-kernel&m=154729716614104
```
This make the GPIO label for HDMI hotplug more consistent to the other
boards.
```
(`HPD_N` -> `HDMI_HPD_N`)
Yes, the 3b .dts was the odd one out.

3. https://marc.info/?l=linux-arm-kernel&m=154729707714068
```
The RPI 3 B+ provides control to both LEDs (PWR and ACT). So append
the first letter of the LED color (like in the schematics) in order
to clarify this.
```
This change is OK, but makes more sense after 4 (I spent a while looking for STATUS_LED_G).

4. https://marc.info/?l=linux-arm-kernel&m=154729713714098
```
The GPIO sysfs is deprecated and disabled in the defconfig files.
So in order to motivate the usage of the new GPIO character device API
add the missing GPIO line names for Raspberry Pi 2 and 3. In the lack
of full schematics i would leave all undocumented pins as unnamed.
```
The bcm2836-rpi-2-b.dts additions look correct.

In bcm2837-rpi-3-b-plus.dts you have SMPS_SDA and SMPS_SCL swapped, but otherwise it seems OK. The names aren't all identical to the schematics, but the functions are correct.

There are multiple revisions of the 3B, and the gpio-line-names in bcm2837-rpi-3-b.dts look like a combination of a few of them, not preciselay matching any of them.

**Comment by lategoodbye** [comment]
Unfortunately the window between rc1 and the moment we need to send our pull requests (usually after release of rc3) is very small. So after receiving no feedback to my patch series i created this issue and needed to apply them shortly afterwards because they must hang out in linux-next for some days, before sending out the pull requests. But it's never too late for a review, so thank you very much for your feedback. I will take care of them in the next round.
