### ISSUE TITLE
sdhci-bcm2708 module build

### ISSUE THREAD

**Issue by tomkcook** [raspberrypi/linux#298]
The kconfig allows CONFIG_MMC_SDHCI_BCM2708 to be set to 'm' for module compilation, but the build fails.

Problems:
- `enable_llm` is defined in sdhci-bcm2708.c (part of the module) but used in sdhci.c - which is either part of a separate module or part of the kernel image, depending on the configuration.  Suggest moving it to sdhci.c and `EXPORT_SYMBOL_GPL`.
- `sdhci_spin_lock` and `sdhci_spin_unlock` are used in sdhci-bcm2708 but are not exported from sdhci.c - suggest `EXPORT_SYMBOL_GPL` in sdhci.c.
- sdhci.c uses `frc_clock_ticks32` which is not exported.  Suggest either `EXPORT_SYMBOL_GPL` in bcm2708 or (maybe better) exporting and using the more generic names `timer_read` or `clksrc_read`.

However, while doing these things produces a buildable module, it still doesn't work.  Loading it doesn't produce any MMC devices in the kernel and certainly not a mountable partition.

**Comment by hvenzke** [comment]
MMC_SDHCI_BCM2708  must be Y  otherwise the usage of class 6 & 10 SD cards failed.

@popcornmix  please move this one and the DMA  to bolean instead tristate for all RPI - if not allready done.

this is from BRANCH=next rpi-update kernel 3.8.11  .

<pre>
zcat /proc/config.gz | grep MMC
CONFIG_MMC=y
# CONFIG_MMC_DEBUG is not set
# CONFIG_MMC_UNSAFE_RESUME is not set
# CONFIG_MMC_CLKGATE is not set
# MMC/SD/SDIO Card Drivers
CONFIG_MMC_BLOCK=y
CONFIG_MMC_BLOCK_MINORS=8
CONFIG_MMC_BLOCK_BOUNCE=y
# CONFIG_MMC_TEST is not set
# MMC/SD/SDIO Host Controller Drivers
# CONFIG_MMC_ARMMMCI is not set
CONFIG_MMC_SDHCI=y
CONFIG_MMC_SDHCI_IO_ACCESSORS=y
CONFIG_MMC_SDHCI_PLTFM=y
# CONFIG_MMC_SDHCI_PXAV3 is not set
# CONFIG_MMC_SDHCI_PXAV2 is not set
CONFIG_MMC_SDHCI_BCM2708=y
CONFIG_MMC_SDHCI_BCM2708_DMA=y
CONFIG_MMC_SPI=m
# CONFIG_MMC_DW is not set
# CONFIG_MMC_VUB300 is not set
# CONFIG_MMC_USHC is not set
uame -a
Linux app1 3.6.11+ #434 PREEMPT Wed May 1 21:13:52 BST 2013 armv6l GNU/Linux
</pre>

**Comment by hvenzke** [comment]
@tomkcook  can you test and report back please with MMC_SDHCI_BCM2708 =y

with 3.6.x 3.8.x we here expirences multible issues  for SHDC/SHDX Cards and where not shure where they from .

If the sdhci-bcm2708.c code been brocken up , that may an reason for probaly .

**Comment by tomkcook** [comment]
@remsnet I'm not sure I follow all of that.  What "multiple issues"?

It would be very useful for me for the sdhci-bcm2708 code to be fixed so that it does load as a module rather than just disabling the option to do so.  I'm trying to debug a system hang in 3.6.11-rt31 which only happens when sdhci-bcm2708 is built in - and without being able to load it as a module, there's no way to get kgdb onto it.

I'm happy to have a go at debugging this myself, but hoped someone with more experience with the code would have some quick advice to offer.

**Comment by hvenzke** [comment]
please  kindly  go your self,  read the past 20 issue , review them .

we faced with current till 3.9.1 stabilty issues with class 6 and 10 cards that block the 3.8.y tree to become MAIN.
Either my self sd cards blamled on daily base.

it wuold be usefull if you follow them and maybee  assist popcornmix fix the code issues.

**Comment by hvenzke** [comment]
my DMA issue are closed  with usage of 3.11.6

**Comment by hvenzke** [comment]
updated to sefcompiled 3.11.y == 3.11.10-1 : no DMA issue., Close if you wistch.
