### ISSUE TITLE
TDK S708G1230 (SDHC, 8 GB, class 10) broken in Linux

### ISSUE THREAD

**Issue by edgmnt** [raspberrypi/linux#315]
This card works fine in my USB card reader (cheap Intenso). Also the firmware seems to be handling it alright and a friend is using it in a camera.

But after the initramfs finishes, it goes on to activate LVM/MD arrays and freezes for a moment. Then it starts spewing out messages like this, and everything else halts waiting for that:

mmc0: Controller never released inhibit bit(s)
mmc0: Timeout waiting for hardware interrupt - cmd13
mmc0: Timeout waiting for hardware interrupt - cmd13
mmc0: Timeout waiting for hardware interrupt - cmd13

And so on. I run a Raspbian I bootstrapped myself and I have tested vmlinuz-3.2.0-4-rpi, vmlinuz-3.6-trunk-rpi, as well as the latest 3.9 from the firmware repo.

I first tried a Nexus 4 supply (5V, 1.2A), but that had a pretty bad cable (I got about 4.7 V across the TPs). Then I tried another phone charger rated at 5V, 0.7A. In both cases, it failed the same way. And mind it's a rather bare debootstrapped Raspbian, and the error happens early on, while booting.

I also tested another identical card with official Raspbian images from raspberrypi.org, and using a different Raspberry Pi too. I also tried messing with the enable_llm / sync_after_dma options, but that didn't change anything.

Any idea what's going on and/or how it can be fixed?

**Comment by hvenzke** [comment]
@edgmnt  well see ..bugLog #280

@popcornmix , ext4 fixed an strange BUG at 3.9.10  that i.e caused some card coruptions as well. 
see http://article.gmane.org/gmane.comp.file-systems.ext4/38504

How far can we test that at Branch next ?

**Comment by hexameron** [comment]
I have just invested in a 4Gb Kingston class 4 card that will not boot without:
"init_emmc_clock=50000000"

i have no idea why that would be needed because it is already the default set in the kernel:
#define BCM2708_EMMC_CLOCK_FREQ 50000000

Which conflicts with the oddly named firmware patch: 
Increase emmc clock to 100MHz to "help" with sdcard corruption when overclocking

https://github.com/raspberrypi/firmware/commit/831239e34138f463d1aaf6e00c096e7db851014c

**Comment by hvenzke** [comment]
@hexameron 

IF you want an STABLE   RPI then stop using overclock at all.
This are the most  result  of descussions done here since past year.

**Comment by ghollingworth** [comment]
Actually that's not true, the most recent work has produced a sdcard fix that was causing corruption and so far with the latest kernel (rpi-update required) I've not seen any further reports of errors

Is this with the latest kernel?

Gordon

**Comment by hexameron** [comment]
I was not able to overclock my 256ModelB Pi, I may not have tried on 512.

Perhaps I should explain.

Using the latest (3.10), selfbuilt. I am obviously doing something wrong
because I do not have available
 DMA slots to run the latest framebuffer code and still boot from sdcard,
so I reverted that.

My Transcend 8GB C10 card has been using 50Mhz emmc since Dom upgraded the
firmware to use 100Mhz and it failed for me.

I got a new 4Gb C4 card to try RaspBMC and it boots perfectly well from
that pre-built kernel, and kernel-emergency. When  I install my own kernel
I need the lower emmc to start raspbmc/debian without fatal read errors. I
do not expect the Foundation to support self-built kernels, I only mention
it because others may have similar problems.

**Comment by hexameron** [comment]
Problem Solved: my kernel was overwriting the Bootloader command line, which was preventing the DMA from being properly set up, and also the correct emmc speed was not being passed to the kernel.... oops.

The Kingston 4G class 4 is listed on the wiki as a bad card, with the failures I was getting. I can confirm that it is working in kernel-next, and linux 3.10.1 WHEN the default command line is passed to the kernel.

**Comment by popcornmix** [comment]
@edgmnt 
Are you seeing this issue with latest rpi-update kernel?
