### ISSUE TITLE
When I move windows there are artifacts around 

### ISSUE THREAD

**Issue by xlazom00** [raspberrypi/linux#3641]
**Describe the bug**
When I move windows in  new 64bit raspbery debian based distro there are artifacts around windows

**To reproduce**
start 64bit debian raspberry pi distro on Pi4 with desktop environment, start terminal and move with window

**Expected behaviour**
no artifacts

**Actual behaviour**
artifacts around window

**System**
official beta 64bit debian 10  for raspberry pi 
Pi4 2GB ram
linux 5.4

**Comment by pelwell** [comment]
We have a dedicated repo for the 64-bit OS: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit

Please create the issue there.

**Comment by xlazom00** [comment]
@pelwell same behavior on 32bit raspbian

**Comment by xlazom00** [comment]
It is visible when I move from right to left and back

**Comment by pelwell** [comment]
Are they temporary glitches or do they remain when you have stopped moving the window?

**Comment by xlazom00** [comment]
Just temp. All fine when I stop.
 I did same test with 32 bin raspian latest version and same behavior

**Comment by xlazom00** [comment]
Are you able to reproduce my problem?

**Comment by pelwell** [comment]
I see some tearing, but nothing that I would call artifacts. Try and capture a video showing the problem.

**Comment by xlazom00** [comment]
Right it is tearing. any plans to fix this?

**Comment by JamesH65** [comment]
It's on the list. Not sure yet what causes it, and because it doesn't affect functionality i.e. it's only cosmetic, it's low priority. Fixing tearing for video playback is also on the list, higher priority, may even be the same cause.

**Comment by xlazom00** [comment]
PI4 is marketed as "desktop" computer and this is really lame bug

**Comment by JamesH65** [comment]
Lame or not, its purely cosmetic and when we have fixed all the higher priority bugs that DO affect actual functionality, then we can look at it. Nothing to do with "desktop" marketing at all.

**Comment by pelwell** [comment]
Closing this lame bug report.

**Comment by codicusmaximus** [comment]
How on earth did this get closed when the problem wasn't even resolved?  Seems like a pretty hostile response @pelwell -- the number of downvotes should be pretty telling.

Just because this is "cosmetic" and there are higher priority bugs doesn't mean this is one should be marked as resolved, complete or closed @JamesH65

I propose this be reopened or if there is another bug in for the screen tearing issue, this issue be linked to that one for proper tracking.  I don't see it anywhere in the 64-bit issue tracker.

**Comment by JamesH65** [comment]
It was closed because 1) We know all about it and are looking in to it, but mainly 2) Because we are just getting an endless stream of "this is a lame bug" which are pointless additions to the issue.

We make 20 thousand Pi's a day, 11 downvotes it not that telling. BUT, we are working on this because we know it is an issue.

As for tracking, there is nothing to track. it'll get fixed when it get fixed (probably official release of KMS).

**Comment by codicusmaximus** [comment]
So there is an issue, it is a known issue, work is being done on it, yet there's nothing to track.  In an issue tracker.  Makes sense to me 🙃

**Comment by JamesH65** [comment]
Good, makes sense to us as well.

**Comment by codicusmaximus** [comment]
The open source community at its finest!

**Comment by codicusmaximus** [comment]
I'm just gonna return my Pi's and move to a platform with leadership that doesn't have their heads up their own butts.  Bye!

**Comment by P33M** [comment]
> I'm just gonna return my Pi's and move to a platform with leadership that doesn't have their heads up their own butts. Bye!

Thank you for your valued contribution to open source software.
