### ISSUE TITLE
Mixed versions?

### ISSUE THREAD

**Issue by jstuckle** [raspberrypi/linux#384]
The 2013-09-10 version of Raspbian seems to have mixed versions.  uname -a shows version 3.6.8, but the /lib/modules directory has a directory 3.6.11+.

The first indication I had was a message at boot time (easy to miss if you're not watching) that file /lib/modules/3.6.8/modules.dep.bin is missing.  It would be since there is no 3.6.8 directory.

**Comment by asb** [comment]
There's something very weird going on with your setup, as the kernel.img on that image is definitely 3.6.11+:

```
asb58@lathkill /media/boot $ dd if=kernel.img bs=1 skip=17836 | zcat | strings | grep -i "Linux version"
Linux version 3.6.11+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #538 PREEMPT Fri Aug 30 20:42:08 BST 2013
2806444+0 records in
2806444+0 records out
2806444 bytes (2.8 MB) copied, 2.3611 s, 1.2 MB/s

gzip: stdin: decompression OK, trailing garbage ignored
asb58@lathkill /media/boot $ man dd
asb58@lathkill /media/boot $ cat issue.txt 
Raspberry Pi reference 2013-09-10 (armhf)
Generated using spindle, http://asbradbury.org/projects/spindle/, 1a9ec88, stage4-lxde-edu.qed
asb58@lathkill /media/boot $ 
```

Could you give any more info?

**Comment by popcornmix** [comment]
@jstuckle 
Can you post complete dmesg log (to pastebin type site) and output of
uname -a
vcgencmd version

**Comment by jstuckle** [comment]
Hmnmm, then it looks like I got something wrong when installing it.  I'm going to have to go back over the steps and see what I missed.

I'm still pretty new on Raspbian (and a bit green on Debian in general), so it's a good possibility.

Thanks.

**Comment by jstuckle** [comment]
OK, I found what I did wrong.  I'm actually trying to run this under qemu, and was using the old kernel in the -kernel parameter.  I tried pulling the kernel file off of the boot partition and using it instead, but the system won't boot (just a black screen).

So, what do I need to do to make the new kernel usable under qemu?  I've searched the internet but haven't found much.

Sorry for the panic - I figured I must have done something wrong, but being rather new here I didn't know what.

TIA.

**Comment by popcornmix** [comment]
qemu won't emulate the pi kernel - it has no knowlege of the hardware features of the pi.
You need to use the qemu specific kernel.

**Comment by jstuckle** [comment]
I find it very presumptuous of you to close this problem without my permission.  This is MY problem, not yours, and I determine when it is fixed, not YOU.

As a matter of fact, the problem is NOT fixed, although it has changed somewhat.  I still cannot run Raspbian 3.6.11+ under QEMU, which I need.  I am developing drivers and programs for a client, and they are not going to pay me to wait hours for the code to compile on the RPi.  Additionally, since I am developing modules, I need to be able to compile my own kernel (the ones out there don't have all of the required headers), and the cross-compile on Debian Wheezy is still not working well.

So I have a choice - get Raspbian running under QEMU or tell my client their choice of devices was bad due to poor support, and they need to go with another device which is better supported.

Which should it be?

**Comment by asb** [comment]
This is not a useful attitude.

Now ignoring that, there is no reason at all to expect the compiled kernel we ship to run under qemu. You could compile a kernel for the versatilepb and boot that on qemu with an emulated arm1176. You'll need to modify the kernel kconfig to allow armv6+versatilepb using something like http://www.landley.net/hg/aboriginal/file/556a5bc3c8a4/sources/patches/linux-arm.patch.

If you're having problems cross-compiling the kernel you're best off asking on the forums.

**Comment by jstuckle** [comment]
Closing a problem without the owner's agreement is not a useful attitude.  It is very presumptuous.  And don't blame me for YOUR attitude.

If it's so easy to build a kernel that runs under QEMU, then why not provide one?  It would be much LESS work for you to do it when building the rest of the system than it is for me to fight trying to download everything necessary to cross-compile (which, as I indicated, is not well supported under Debian Wheezy yet - I've checked). 

So I guess I'll go back to my client and tell them the RaspberryPi will not make a good controller for their systems and they need to pick something else.  They won't be happy, but they would be a lot less happy if I presented them a bill for hours of bench time waiting for code to compile.  This may be fine for experimenters - but not for business.

**Comment by notro** [comment]
Talking about attitude: You are critizing this project for not fitting YOU?
This project goes where it's contributors takes it. You are free to make a rock solid distro to be used in controllers. But that takes time, and someone has to invest that time.
The Raspberry Pi Foundation does contribute to this kernel and Raspian, but their ultimate goal is Education.

**Comment by JamesH65** [comment]
I'm sorry, but this is not your website, it's the Foundation's and the people who run it have the last say. You do not 'own' the problem, or your posting on the subject. You attitude is rather more presumptuous I would have to say.

With regard to support. Many of the people working on these problems are unpaid. You are paid. And yet you are the one complaining about lack of support...ironic.

**Comment by jstuckle** [comment]
@notro - No, I'm criticizing the project for not fitting all those people out there who are using QEMU to try to emulate the RPi for various reasons.  And it would take much LESS time for someone who's already building a distro to add a QEMU-supported kernel to the mix than someone else to build another (possibly incompatible with the current one) distro.

@JamesH65 - no, I do not own the site.  But it is still MY PROBLEM.  Yes, I am getting paid.  But I am NOT getting paid for sitting on my backside waiting for hours for a compile to finish on the RPi.  

I've been a consultant for 23 years now.  Before that, I spent 13 years with IBM, both in hardware and software.  And when a customer has a problem, it is the CUSTOMER'S problem - not mine.  And I would NEVER close a problem without customer concurrence.

No, it is not I who is presumptuous.  It is the people who run this board.

Never fear - I have already pointed my client to this thread and they are reconsidering their idea to use the RPi.  A shame, because this will be going into a commercial product and it could have been great publicity for the Foundation.

I REALLY don't think you understand how your attitude comes across to the rest of the world.  But then I also have to think you don't care.

**Comment by JamesH65** [comment]
Well, if your client is reading this thread....

Dear Client, 

The Raspi is probably quite capable of being used in your product. It's a cheap but powerful device. But what it doesn't come with is the sort of support that your engineer is demanding, quite rudely. Let's be honest, at $35 a pop, that doesn't pay for any support whatsoever, and ever since launch, the Raspberry PI has been supported by it's community of getting on for a million users. This community is good, but they mostly work for free, and may not have the answers to all questions. Demanding answers from a community as your engineer is doing shows a lack of respect for the time put in by those volunteers.

I would be more concerned about the people you are employing to develop your product, rather than the Raspi itself. Setting up a cross compiler is not 'rocket science', and is covered extensively by various websites. You have to  question why problems are being encountered in this area, on something that should take no more than a day to sort out.

Regards

A volunteer.

**Comment by jwilker2** [comment]
@jstuckle - Wow, thanks for the resume ... Now demonstrate that you can evolve to the level of the rest of us and learn to CROSSCOMPILE. I7 + compiler + some skill = 5 to 7 minute compile time.

These gentlemen and this board were not instituted to do your work for you but rather to assist a diverse and developing community. Incidentally most of whom are contributing their time gratis.

Stop flaming the board and move on...

**Comment by JamesH65** [comment]
Cool. I've just realised that as of next week I will have been writing software for 33 years, 27 of those professionally, in many customer facing roles. 

Just thought I'd mention it since we were on the subject of resumes.

Oh, obligatory relevant link..How to crosscompile for the Pi...by curious coincidence, this thread was recently resurrected on the Raspi website.

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=31&t=8478

**Comment by jstuckle** [comment]
@JamesH65 - ROFLMAO.  I have a long history with this client.  They know my technical expertise - which is why they asked me to do this project.  I'll be interested to see what their response is to your attempt to smear me is.  

@jwilkere2 - if it only takes 5-7 minutes, then it should be easy for those who are building the kernels to do so.

But obviously you haven't read the previous posts.  I would have to first build a cross-compiler - there isn't anything currently available for Debian Wheezy.  Then I would have to figure out the options to compile a compatible kernel and get it to compile.  Then there is the testing to ensure it is compatible.  We're talking days here, not 5-7 minutes.

**Comment by P33M** [comment]
Alright, that's enough.

The Github repositores and associated discussions currently have a very high signal to noise ratio. It is of immeasurable benefit to the Foundation that volunteer effort provides such a large amount of quality code as patches to our kernel and userspace applications. So much so that many of the Github repositories hosted are actually administered by volunteer effort.

For information, there are no people that have posted in this thread that are employees of the Foundation or its trading subsidiary, with the exception of myself.

This discussion has run its course, and further posts will just fall apart into a flame war.
