### ISSUE TITLE
Add CAN_ISOTP Kconfig flag for Kernel 5.10

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#3900]
Hi,

there is an upstream Kconfig flag that is valuable to catch. It is currently queued for net-next.

https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/diff/net/can/Kconfig?id=2ad119d998e49003327b81edb7b854d0983b5d58

It would be great to have ISOTP CAN Protocol enabled by default on the raspberry pi, e.g. CAN_ISOTP=Y .

Thanks and Best Regards

**Comment by 6by9** [comment]
You're a bit premature. There are no 5.10 release candidates yet, therefore no rpi-5.10.y branch that could possibly add that config.

As it's a builtin option rather than a module it also needs to be evaluated for the amount of RAM it will consume on EVERY system, whether they care about CAN or not. At least a module only consumes some amount of storage space.

**Comment by ghost** [comment]
It is a module, not builtin. You could label it with the corresponding milestone for rpi-5.10.y for example.
BTW: All other CAN related modules are enabled as far as I know.

**Comment by 6by9** [comment]
You'd requested ```CAN_ISOTP=Y ``` which would make it built in.

We don't generally use milestones as they are an additional admin overhead to then marshal.

**Comment by ghost** [comment]
Ooops, that's due to copy and paste, sorry. Please make it an M.

**Comment by ghost** [comment]
I've noticed rpi-5.10.y branch is up and made a pull request.
Sorry for the noise.
