### ISSUE TITLE
There are some grammatical mistakes in Documentation/xz.txt

### ISSUE THREAD

**Issue by divz11** [raspberrypi/linux#3920]
**There is some grammatical mistakes in the file xz.txt which I think should be removed.**

**Comment by 6by9** [comment]
Thanks for your contribution.

This is a pure upstream file, so any fixes ought to be submitted upstream rather than here.

Please note that upstream have moved it to [Documentation/staging](https://github.com/torvalds/linux/blob/master/Documentation/staging/xz.rst), and converted it to ReST format instead of a simple text document.

**Comment by pelwell** [comment]
Next time, don't open an issue and a PR about the same thing - go straight for the PR.
