### ISSUE TITLE
Network flip flop

### ISSUE THREAD

**Issue by ottuzzi** [raspberrypi/linux#429]
Hi,

   since when I upgraded the venerable 3.6.11+ I noted on all newer kernels a kind of network flip flop at boot. Something like this:

<pre>
[   22.772034] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   24.537515] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   25.279144] bcm2835-cpufreq: switching to governor ondemand
[   25.279174] bcm2835-cpufreq: switching to governor ondemand
[   25.408311] smsc95xx 1-1.1:1.0 eth0: link down
[   27.001218] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   27.833748] smsc95xx 1-1.1:1.0 eth0: link down
[   29.450200] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   29.647750] Adding 102396k swap on /var/swap.  Priority:-1 extents:1 across:102396k SS
[   30.266133] smsc95xx 1-1.1:1.0 eth0: link down
[   32.122655] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[   32.954562] smsc95xx 1-1.1:1.0 eth0: link down
[   34.571877] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[   35.386973] smsc95xx 1-1.1:1.0 eth0: link down
[   37.003071] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x4DE1
[   37.819097] smsc95xx 1-1.1:1.0 eth0: link down
[   39.453573] smsc95xx 1-1.1:1.0 eth0: link up, 10Mbps, full-duplex, lpa 0x4C61
</pre>

Network goes up and down many times and then it just stabilizes: not a major issue... just curiosity on my side. Did anyone saw something similar? If I remember correctly on 3.6.11+ network did not switch back and forth so many times...

Thanks
Bye
Piero

**Comment by ruuns** [comment]
I can confirm this issue on my device using arch arm distribution. 

```
[root@alarmpi ~]# uname -a
Linux alarmpi 3.10.24-1-ARCH #1 PREEMPT Fri Dec 13 01:21:41 CST 2013 armv6l GNU/Linux
```

dmesg returns the following output at boot up:

```
[    8.834205] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   10.401782] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[   46.150249] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   46.254166] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   47.812140] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
```

**Comment by popcornmix** [comment]
Insufficient power supply would cause this behaviour:
http://elinux.org/R-Pi_Troubleshooting#Troubleshooting_power_problems

**Comment by ruuns** [comment]
I've checked my internal voltage between TP1 and TP2 during the booting process. It's constantly between 4.75V and 4.77V (with and without HDMI/Keyboard connections).  It can be caused by my power supply (my power cable/supply is currently only a workaround). 

I was also wondering at first because it seems this issue is only occuring at startup and later it stabilizes again (like it waits for all condensators until they are fully-charged). I'll try a more proper power supply.

**Comment by ottuzzi** [comment]
Hi there, it looks like that in my case it was a faulty network connection, not a raspberry or kernel problem. So, if ruuns agrees we can close this issue. 

Thanks for your work 
Bye 
Piero

**Comment by onzulinapps** [comment]
Hello, I have same problem, smsc95xx 1-1.1:1.0 eth0 : hardware isn't capable of remote wakeup 
IPv6: eth0 link is not ready 
how could I resolve my problem? regards

**Comment by shelteroperations** [comment]
Same problem since Maybe January (Rpi 3, Raspbian):

smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup

Ideas???

**Comment by pelwell** [comment]
If that's the only error message then there isn't a problem - it's just a statement of fact. Is your Pi3 malfunctioning in some way?

**Comment by shelteroperations** [comment]
It dies every few days. It's remote so "dying" might not be "dying" but that I can't get into it without someone hard rebooting, then.... /var/log/messages shows this as the last message before I couldn't get in. I just installed ifplugd then ran  sudo update-rc.d ifplugd enable. I don't know, maybe a bandaid, but we'll see.

**Comment by pelwell** [comment]
I can't check right now, but I think that message will be displayed every time the interface is brought up, so seeing it repeatedly in the log could be a symptom of some sort of network flakiness.

**Comment by shelteroperations** [comment]
Seems slow to login...... latest messages in /var/log/messages:

Jun  4 17:09:35 mana31 kernel: [   23.726264] random: 7 urandom warning(s) missed due to ratelimiting
Jun  4 17:09:37 mana31 kernel: [   25.914791] r820t 4-001a: destroying instance
Jun  4 17:09:37 mana31 kernel: [   25.916363] dvb_usb_v2: 'Realtek RTL2832U reference design:1-1.4' successfully deinitialized and disconnected
Jun  4 17:09:47 mana31 kernel: [   35.813546] r820t 6-001a: destroying instance
Jun  4 17:09:47 mana31 kernel: [   35.814084] dvb_usb_v2: 'Realtek RTL2832U reference design:1-1.5' successfully deinitialized and disconnected
Jun  4 17:16:08 mana31 kernel: [  416.443273] device eth0 entered promiscuous mode
Jun  4 17:21:25 mana31 kernel: [  733.407713] device eth0 left promiscuous mode
Jun  4 18:00:10 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:00:40 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:01:18 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:01:48 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:05:15 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:05:45 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:07:03 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:07:33 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:09:01 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:09:31 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:10:15 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:10:45 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:10:45 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:11:15 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:11:17 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:11:47 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:15:25 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:15:55 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:16:01 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:16:31 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:17:01 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:18:01 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:18:04 mana31 rsyslogd-2007: action 'action 17' suspended, next retry is Mon Jun  4 18:19:04 2018 [try http://www.rsyslog.com/e/2007 ]
Jun  4 18:18:12 mana31 kernel: [ 4140.721808] device eth0 entered promiscuous mode
Jun  4 18:18:22 mana31 kernel: [ 4150.665603] device eth0 left promiscuous mode

**Comment by JamesH65** [comment]
If you remove the DVB-T adapter, does it work correctly?

**Comment by shelteroperations** [comment]
There is no HDMI plugged in or any video if that's what you're asking. It runs text-only.

**Comment by JamesH65** [comment]
The log you posted has a reference to a 'Realtek RTL2832U reference design:1-1.4. That's a DVB-T adaptor. Is it plugged in? Or is it an artefact of a particular kernel build? I'm not sure why its appearing in the log.

**Comment by shelteroperations** [comment]
Woops I read that quickly as the Ethernet adapter. I have two RF (radio frequency) USB sticks plugged in. But they've been plugged in for over a year, no problems at all, and used for service. I don't know why it keeps crashing.

**Comment by JamesH65** [comment]
It would be worth removing them and seeing if the problem goes away. Could be a interaction between them. We've had similar before between Wireless and onboard ethernet - should've be independent. Turns out  they were not under some very specific circumstances.

**Comment by shelteroperations** [comment]
Would sort of defeat the purpose of the Rpi there then. And as I mentioned no problems in over a year. Unless it's hardware failure. Would it help to install a USB hub so all those signals weren't "right next to" the ethernet port?

**Comment by shelteroperations** [comment]
I also uninstalled a bunch of packages recently I read in forums or wherever that were unnecessary and were just eating memory. I don't have a list of those, but is there any chance I uninstalled something that I needed? Is there a message that could help us understand if this were the case?

**Comment by JamesH65** [comment]
When diagnosing a problem, you reduce the problem space until the problem goes away. We are simply trying to narrow down what the issue might be, and removing possible causing of the problem helps with that. 

You might have uninstalled something important, impossible to tell. You need to start afresh with a new SD card, and also try with unusual peripherals removed. Add then add things back until the problem reappears.

**Comment by shelteroperations** [comment]
This is a true statement. As I noted though it's a remote machine we're using for something. I can try that if nothing else works next time I'm there. It hasn't crashed yet after I installed the ifplugd I mentioned above but it's only been a day. Still even if that's the case it sounds like a bandaid. As you initially noted it could also be the ethernet switch it's plugged into. I can't test any now remotely. I was just wondering if anything glaring jumped out at you, software related. Thank you for your kind help.

**Comment by pelwell** [comment]
It seems you can safely ignore (or even suppress) the "action 17" messages: https://raspberrypi.stackexchange.com/questions/47781/what-is-action-17

**Comment by shelteroperations** [comment]
Thanks.

**Comment by iiv3** [comment]
After upgrading to "testing" I got a serious problem where rpi would obtain IP through DHCP, but then bring Ethernet down, sometimes multiple times and then it would not respond, even to disconnecting and reconnecting the lan cable.

The logs also showed a bunch of "hardware isn't capable of remote wakeup".

After numerous tries I solved the problem with removing "avahi-daemon".

I do suspect that the above message is related to the lan driver not been able to handle multicast properly and doing something wrong with the lan card.

So, if you have similar problem, avoid everything that might be using multicast.

Just to be clear, multicast is when networks uses groups with IP addresses from 224.0.0.0 to 239.255.255.255. Other than "avahi", it could be used by "upnp" and even "ntp" stuff.

**Comment by lamazze** [comment]
After upgrading my raspberry 3B from Jessie to Buster, I started experiencing "wlan0: carrier lost" problems once a day .
I've tried different solutions but stopping avahi service apparently solved the problem. Thanks for the suggestion!
Edit: finally disabling wicd, avachi-daemon and networking solved all the wifi connection problems.
