### ISSUE TITLE
Documentation regarding bcm2708 specific module parameters

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#440]
Is it possible to get documentation regarding newly introduced module parameters?

Digging through forum posts or issues is quite time consuming and I guess a single point to find information about these parameters will help people when debugging or resolving issues.

When reading a forum post like http://www.raspberrypi.org/phpBB3/viewtopic.php?t=12097&p=161483 to fix an issue using a module parameter 'enable_llm' does not explain why this parameter resolves the issue and the effect of this parameter still remains black-magic.

Of course these new parameters can be looked up in the kernel source, but why and when they should/could be used isn't clear.

The wiki pages (on Github) for both the linux kernel and firmware lack information about these RaspberryPi specific kernel options. 

Several parameters are introduced to resolve issues in specific use cases and some options are a better choice than others (sync_after_dma vs missing_status). But documentation (other than the comments in code) is lacking background information what these options do and which scenario would benefit from them.

**Comment by popcornmix** [comment]
The default module parameters are right for 99% of users.
In general non-default options are only implemented to help with tracking down bugs (rather than working around them), so they will normally be suggested by a developer in response to a bug report (on github or forum).

Feel free to create a page (e.g. on http://elinux.org) listing the kernel module options you have seen described, a brief description and a link to the source of this information.

I'll try to correct any mistakes and fill in any gaps.

**Comment by ghost** [comment]
My guess is that 1% is doing stuff with odd hardware/software and is able to solve their own issues when able to find proper information. 
I'll search for module parameters specific for the bcm2708 and add them to a page on eLinux.org, Thanks in advance.
