### ISSUE TITLE
cheese in wheezy have unmet dependencies

### ISSUE THREAD

**Issue by petterreinholdtsen** [raspberrypi/linux#443]
When I try to install cheese after updating all my apt sources, I get this error message:

root@raspberrypi:~# apt-get install cheese
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cheese : Depends: libcheese-gtk21 (>= 3.4.0) but it is not going to be installed
          Depends: libcheese3 (>= 3.4.0) but it is not going to be installed
          Depends: libclutter-1.0-0 (>= 1.10.0) but it is not going to be installed
          Depends: libclutter-gtk-1.0-0 (>= 0.91.8) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@raspberrypi:~# 

These are the APT sources I have enabled:

deb http://raspberrypi.collabora.com wheezy rpi
deb http://archive.raspberrypi.org/debian/ wheezy main

Any idea what is wrong?  Some library or cheese itself need a rebuild?

**Comment by popcornmix** [comment]
Sorry this repo is for the linux kernel. raspbian distribution issues are better asked here:
http://www.raspberrypi.org/phpBB3/viewforum.php?f=66 or
http://www.raspbian.org/

**Comment by petterreinholdtsen** [comment]
[popcornmix]

> Sorry this repo is for the linux kernel. raspbian distribution
> issues are better asked here:
> http://www.raspberrypi.org/phpBB3/viewforum.php?f=66 or
> http://www.raspbian.org/

Ah, sorry for the confusion.  Reported as
<URL: https://bugs.launchpad.net/raspbian/+bug/1253435 > now.

## 

Happy hacking
Petter Reinholdtsen

**Comment by asb** [comment]
Plugwash and others probably won't like the issue on that tracker as it's
actually related to packages external to upstream wheezy we distribute on
the standard image. The problem is that some libraries (annoyingly) depend
on libegl-mesa, which in turn depends on a particular version of
libwayland0. The collabora repo, provides a newer version and so we end up
with dependency issues. You could remove the collabora repo from
/etc/apt/sources.list.d and apt-get remove libwayland0, then try again. I
wouldn't expect cheese to be very usable on the pi though. This discussion
should be continued on the forums (and people have probably raised the same
issue there before).
