### ISSUE TITLE
support for overlayfs

### ISSUE THREAD

**Issue by bklier** [raspberrypi/linux#447]
Would it be possible to integrate overlayfs into the rpi kernel? That would be great for building rasperry systems which will be better protected from power failures (so they will not crash the filesystem due to unclean shutdowns...)

Re
Benjamin Klier

**Comment by asb** [comment]
Unless I'm very much mistaken overlayfs hasn't made it upstream right? We generally don't like to accept non-upstreamed patchsets due to the maintenance burden. Plus overlayfs is far from the last word in this area (people will ask, why not aufs, or...). Have you looked at using devicemapper thin provisioning as Docker is moving to (it's moving from aufs as distros like RHEL don't want to carry out of tree patchsets like that either).

**Comment by bklier** [comment]
That sounds like a very promising solution - maybe you can provide me with some in depth information about this topic?

**Comment by popcornmix** [comment]
You can use the BRANCH=next firmware or build from rpi-3.18.y kernel tree for this.
