### ISSUE TITLE
emmc clock change in kernel 3.10.24

### ISSUE THREAD

**Issue by TRechlicz** [raspberrypi/linux#467]
The emmc clock defaulted to 100MHz in kernel 3.6.11.  In kernel 3.10.24 it is defaulting to 250MHz.  Even with high end SD cards this results in slower throughput.  Just to do an even comparison I used hdparm -tT /dev/root on both versions of the above kernels. Speeds dropped from ~20 MB/sec in 3.6.11 to ~17MB/sec in 3.10.24.  I can set my emmc frequency in config.txt,  init_emmc_clock=200000000, to obtain ~21MB/sec after that any frequency increase causes throughput to drop off.  Use vcgencmd measure_clock emmc to verify frequency.

**Comment by ghollingworth** [comment]
in kernel 3.6.11 we use /2 to generate a 50MHz clock in 3.10.24 it's /5

So the clock frequency to the device should not change (it should be 50MHz).  Are you saying that if you set the init_emmc_clock back to 100MHz you get 20MB/sec again? (along with the associated corruption of course!)

Gordon

**Comment by TRechlicz** [comment]
What I have found is running vcgencmd measure_clock emmc on 3.6.11 I get 100000000 (100MHz).  Once upgraded to 3.10.24 and running vcgencmd I now get 250000000 (250MHz) without any changes to the SD card controller in config.txt.  I only started to look at the default emmc clock because running hdparm showed a drop from 20MB/sec to 17MB/sec on my SD card upon upgrading.  As I recall the original emmc clock for the SD card controller on older versions of the kernel was set to 80000000 (80MHz).  This is also described as being the case in the Raspberry PI users guide page 92.  I do not know if we are talking about the same SD card clock controller.

Thanks,
Tom

**Comment by ghollingworth** [comment]
OK,

So that's just because the SD corruption issue was caused by a clock crossing failure between the VPU core clock (which runs at 250MHz) and the eMMC clock (which was 100MHz) by changing the eMMC clock to be the same as the VPU core clock this avoids the cross domain problem.

But to set the actual final frequency (which should be 50MHz) it takes this frequency and divides it with an integer divider so this should not effect the actual frequency of the SD clock.

It is more likely that the difference is to do with the SD card itself or the ext4 partition or file arrangements etc...  To check this I'd suggest you switch back and forth between the two versions and run bonnie++ (you can sudo apt-get it)

There are other changes in 3.10.y which may have caused changes in timing to occur but otherwise I've not noticed it to be different...

Gordon

**Comment by popcornmix** [comment]
I don't believe this issue is valid. The actual emmc _bus_ clock speed has no effect on transfer.
@TRechlicz okay to close?

**Comment by jaredmcneill** [comment]
@popcornmix @ghollingworth the SD host controller (3.0) divided clock mode reg requires the divisor to be a power of two. You can't do 1/5, the driver ends up selecting 1/8 -> 31.25MHz.

**Comment by ghollingworth** [comment]
Actually the driver chooses a value of 1/6 resulting in a frequency of 41MHz...  ((250 / 6) / 50 ) \* 20 = 17MBytes (approx)

**Comment by jaredmcneill** [comment]
Oops, you're right. Well that explains the issue perfectly then!

**Comment by P33M** [comment]
As explained, this is required to work around a bug with the hardware.

An alternative is to use the `dtoverlay=sdhost` parameter in config.txt which will switch to the "Broadcom MCI" hardware (which does not have this issue).
