### ISSUE TITLE
Kernel 5.18-rc4 64bit FKMS boot issue

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#5008]
### Describe the bug

Ever since kernel 5.18-rc3 I am unable to boot in to a Desktop Environment with FKMS. No problem with 5.18-rc2 or 5.15.y or 5.17.y.

With my VIZIO tv I have always had to do a manual config in config.txt with the pi4 for KMS/FKMS or all I get is a black screen. Everything works good with KMS configured to boot but all I get is a black screen with FKMS configured to boot. It is like my manual config in config.txt is ignored.

I hooked up to my Gateway monitor and I can see the lines going by at firs boot but when it tries to go in to graphics mode the screen immediately goes black. I also tried my GW edid.dat file I use every once in a while I put in cmdline.txt but it had no effect.

With both monitors I am unable to log in with ssh. It is like maybe the system is locked up.

### Steps to reproduce the behaviour

Configure config.txt to boot in to FKMS.

### Device (s)

Raspberry Pi 4 Mod. B

### System

`Linux pi4 5.18.0-rc4-1-MANJARO-ARM-RPI #1 SMP PREEMPT Mon Apr 25 19:08:32 UTC 2022 aarch64 GNU/Linux`

```
[ray@pi4 ~]$ vcgencmd version
Mar 24 2022 13:19:26 
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)
```

### Logs

Unable to retrieve any logs.

**Comment by Dark-Sky** [comment]
Today I compiled the latest 5.15.25 and 5.17.4 kernels and they also now have this issue trying to use FKMS. I also installed the latest 5.15.25 64bit kernel on my arch-arm 32bit image and it also has this issue; booting with KMS was still good with it also. It was mentioned a few days ago in another issue here that FKMS was depreciated and not a priority should I just have to forget about FKMS going forward?

**Comment by popcornmix** [comment]
fkms is not actively developed and, is not the default configuration and shouldn't be used as a permanent setting.
If a user has issues with kms (compared to fkms), then fixing that is the priority.
There is no guarantee that fkms will be supported indefinitely.

However fkms can be useful in triaging bugs. i.e. if a configuration works with fkms but not kms then it's likely an issue with the kms driver, rather than, say, an X or application issue.

And it can be used as a temporary means of getting a working display while other remedies are employed (e.g. running long enough to update kernel).

So, feel free to report a regression in fkms. There will be some effort to track down the breakage and fix it, but it won't be the highest priority.

**Comment by popcornmix** [comment]
Can you test https://github.com/raspberrypi/linux/pull/5009

**Comment by Dark-Sky** [comment]
> Can you test #5009

Sure; be glad to.

**Comment by Dark-Sky** [comment]
@popcornmix FKMS is now working again with the new commit on branch 5.15.y. Could you please make commits to 5.17.y and 5.18.y.

I appreciate you taking the time to look in to this. We have some DE's that has issues with KMS from time to time that works with FKMS. Their also seems to be some monitors/tv's that works better with FKMS.

**Comment by pelwell** [comment]
The newer branches are updated now.

**Comment by Dark-Sky** [comment]
Thank you so much!!

Closing issue now...
