### ISSUE TITLE
 “failed to load overlay i2s-mmap” on 84 Kernel RPI Z2W

### ISSUE THREAD

**Issue by ramfish** [raspberrypi/linux#5319]
Hopefully posting this in the right place:
Testing using RPI Z2W and SeeedStudio 2mic WM8690 audio board
Was running well before the latest  kernel upgrade which was performed as part of clean install of SeedStudio (https://github.com/respeaker/seeed-voicecard)
No getting the MMA I2S fail to load
checked and enabled I2C in Config.txt - makes no difference (And was working on previous Kernel)
If somebody needs more debug info be happy to provide

**Comment by pelwell** [comment]
Wow - that overlay (and the driver change that supports it) hasn't existed since rpi-4.4.y, i.e. around 2017. My understanding based on this comment (https://github.com/raspberrypi/linux/issues/1004#issuecomment-297010950) is that MMAP is enabled by default so there is no need for the overlay.

Having looked now, rpi-5.15.y still contains code in `dmaengine_pcm_set_runtime_hwparams` that sets `SNDRV_PCM_INFO_MMAP` and `SNDRV_PCM_INFO_MMAP_VALID`, so there should be no need for the overlay and driver patch.

**Comment by pelwell** [comment]
Hmmm - I see you've already opened an indentical issue in the [respeaker/seeed-voicecard repo](https://github.com/respeaker/seeed-voicecard/issues/333), a better home for it. I'll post the above comment (and follow) there, in case there is any fallout.
