### ISSUE TITLE
WiringPi rendered inoperative by latest update!!!

### ISSUE THREAD

**Issue by ValGretchev** [raspberrypi/linux#5783]
### Describe the bug

The cpuinfo file in /proc directory was modified and no longer includes the Hardware : BCM2835 line. This causes WiringPi to exit as it can’t find the required information rendering all programs that use the I/O and peripherals inoperative.

### Steps to reproduce the behaviour

Raspberry Pi 4B
[proc-cpuinfo-old.txt](https://github.com/raspberrypi/linux/files/13637311/proc-cpuinfo-old.txt)
[proc-cpuinfo-new.txt](https://github.com/raspberrypi/linux/files/13637312/proc-cpuinfo-new.txt)

### Device (s)

Raspberry Pi 4 Mod. B

### System

Latest Raspberry Pi OS 64-bit

**Comment by lategoodbye** [comment]
Is there a chance that WiringPi could be adapted to not rely on these modification to /proc/cpuinfo?

**Comment by 6by9** [comment]
WiringPi is deprecated by all those who supported it.

Gordon dropped it in 2019.

Those who created the fork at https://github.com/WiringPi/WiringPi put it on life-support, but have dropped it as of Oct 2023 with the comment
> This library was deprecated by its author in August 2019. As of 31st October 2023 nobody has shown an interest in properly maintaining it. Between this, and changes to GPIO in Rasberry Pi OS Bookworm and on the Raspberry Pi 5, this project is going nowhere. It has been archived to more clearly indicate this status.

It's not been shipped with Raspberry Pi OS since Jan 2022 due to it bit-rotting.

I would suggest you look into a library using [libgpio](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/) (eg libgpiod for C, or gpiozero for Python), because it is going to break even bigger time when 6.6 becomes the stable kernel (see #5668, https://github.com/WiringPi/WiringPi/issues/186)

**Comment by 6by9** [comment]
Note that sysfs GPIO access has already gone from Ubuntu. See the blog posts by those involved.
https://waldorf.waveform.org.uk/2021/the-pins-they-are-a-changin.html
https://waldorf.waveform.org.uk/2022/the-one-where-dave-breaks-stuff.html

RPi.GPIO got shimmed as https://rpi-lgpio.readthedocs.io/
WiringPi has not been.

**Comment by ValGretchev** [comment]
Perhaps it could but that job is beyond me. I just need to get my application done and move on. I am 82 years old, and time is a wasting.

**Comment by 6by9** [comment]
https://github.com/raspberrypi/bookworm-feedback/issues/129 so deliberate change in the kernel to bring it closer to mainline.

Looking at WiringPi, there is already a `#ifdef DONT_CARE_ANYMORE` around the check for the Hardware line, and it isn't defined. So this check hasn't been enabled for 5 years.
The comment that follows the ifdef would probably be appropriate in this situation - https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L795-L813

**Comment by ValGretchev** [comment]
I see it on line 782 and I will look into it. Thanks for continuing to offer a solution even though you have closed the post. I appreciate it.

Val Gretchev P.Eng.
