### ISSUE TITLE
Java Swing UI blurry or broken

### ISSUE THREAD

**Issue by tatobrutto** [raspberrypi/linux#6138]
### Describe the bug

Hi,
any simple GUI designed with Java Swing (I've used NetBeans) appears blurry and broken.
![photo1714513493](https://github.com/raspberrypi/linux/assets/9320248/9da33c65-5d94-484c-ba0a-b45c85239f8d)

I found this problem in all Bookworm releases but not in Bullseye. This last one works correctly (tested successfully on image 2023-05-03-raspios-bullseye-arm64.img.xz)

Java 11 or 17 does not make any differences.

### Steps to reproduce the behaviour

Write any simple Java form with Netbeans (on Windows or Linux). Compile in a jar and run on Raspbian.

### Device (s)

Raspberry Pi 4 Mod. B

### System

All Bookworm releases also legacy

**Comment by popcornmix** [comment]
This repo if for reporting bugs in the linux kernel.
This issue is not related to the linux kernel, so doesn't belong here.

I'm not sure where the best place to report this is,
but I'd start with the [forum](https://forums.raspberrypi.com) where there may be other users of java swing who can advise.
