### ISSUE TITLE
sc16is7xx driver: missing support for SER_RS485_RTS_ON_SEND

### ISSUE THREAD

**Issue by sonelu** [raspberrypi/linux#6539]
### Describe the bug

At the moment in kernel 6 the struct `serial_rs485 sc16is7xx_rs485_supported` only includes the flag for `SER_RS485_RTS_AFTER_SEND`:  ([link](https://github.com/raspberrypi/linux/blob/80533a952218696c0ef1b346bab50dc401e6b74c/drivers/tty/serial/sc16is7xx.c#L1459C1-L1463C3))

```
static const struct serial_rs485 sc16is7xx_rs485_supported = {
	.flags = SER_RS485_ENABLED | SER_RS485_RTS_AFTER_SEND,
	.delay_rts_before_send = 1,
	.delay_rts_after_send = 1,	/* Not supported but keep returning -EINVAL */
};
```

Because the `serial_core` later on checks the configuration using:

```
static void uart_sanitize_serial_rs485(struct uart_port *port, struct serial_rs485 *rs485)
{
	u32 supported_flags = port->rs485_supported.flags;

	if (!(rs485->flags & SER_RS485_ENABLED)) {
		memset(rs485, 0, sizeof(*rs485));
		return;
	}

	rs485->flags &= supported_flags;

	...
}
```
only the `SER_RS485_RTS_AFTER_SEND` setting would be considered. As a result it is no longer possible to supply a configuration as:

```
rs485conf.flags |= SER_RS485_RTS_ON_SEND;
rs485conf.flags &= ~(SER_RS485_RTS_AFTER_SEND);
```

This could be solved very simple by adding `SER_RS485_RTS_ON_SEND` as a supported flag:

```
static const struct serial_rs485 sc16is7xx_rs485_supported = {
	.flags = SER_RS485_ENABLED | SER_RS485_RTS_AFTER_SEND | SER_RS485_RTS_ON_SEND,
	.delay_rts_before_send = 1,
	.delay_rts_after_send = 1,	/* Not supported but keep returning -EINVAL */
};
```

Let me know if you would prefer me sending a PR with the changes or if this is something that should be rather requested in the upstream kernel git.

### Steps to reproduce the behaviour

Using this configuration will be rejected, although it's perfectly valid and the chip (and the driver) supports it:
```
  struct serial_rs485 rs485conf;
  /* Enable RS485 mode: */
  rs485conf.flags |= SER_RS485_ENABLED;
  rs485conf.flags |= SER_RS485_RTS_ON_SEND;
  rs485conf.flags &= ~(SER_RS485_RTS_AFTER_SEND);
  rs485conf.delay_rts_before_send = 0;
  rs485conf.delay_rts_after_send = 0;
  ioctl (socket_fd_, TIOCSRS485, &rs485conf);
```

### Device (s)

Raspberry Pi 5

### System

System: bookworm
Kernel: 6.6.62+

**Comment by pelwell** [comment]
`drivers/tty/serial/serial_core.c` is an unmodified upstream file - there are no Pi-specific changes to it. You would therefore normally have to send the bug report or the suggested fix to the kernel maintainers. In this case, though, it has already been noticed and fixed in newer kernels: https://github.com/raspberrypi/linux/commit/068d35a7be65fa3bca4bba21c269bfe0b39158a6

It's a shame it wasn't given a `Fixes:` tag, otherwise it would probably already have been back-ported to LTS kernels. However, we are happy to accept back-ports from newer kernels because there is no ongoing maintenance required.

https://github.com/raspberrypi/linux/pull/6540 is that back-port. If you wait about 40 minutes you will be able to install a trial 6.6 kernel using `sudo rpi-update pulls/6540`, after first backing up any important data.

**Comment by sonelu** [comment]
Thank you @pelwell . Outstanding, as always!

**Comment by sonelu** [comment]
Issue can be closed. I confirm that the patch solved the problem.
