### ISSUE TITLE
stk1160 with 3.12.25+ is not working

### ISSUE THREAD

**Issue by pete111** [raspberrypi/linux#660]
Hey, 

when I used 3.10.25+ kernel it works with my stk1160 video capture usb ok. But 3.12.25+ has troubles. Can you revert driver from 3.10.25+ to 3.12?

thanks

**Comment by popcornmix** [comment]
I think you will have to carefully explain the "troubles" before we make any changes to kernel....

**Comment by pete111** [comment]
Hi popcornmix, 

I am new to kernel so I will try to describe what happened: With I used my stk1160 grabber with 3.10.25+ and hyperion with LEDs without any troubles. Then when I use the same RPi, the same grabber, and the same hyperion, but the newest Raspbian 3.12 my leds flicker. Because everything is the same but only Raspbian is the newest with new stk driver - this must be my issue. But what's more I can't use older Raspbian with my model B+. Older raspbian with older stk1160 drivers didn't have this issue.

**Comment by popcornmix** [comment]
Do you still have the issue after running rpi-update?

**Comment by pete111** [comment]
yes, unfortunately  rpi-update didn't help.

**Comment by pete111** [comment]
just for clarification - I tried versions 3.12.22+ and 3.12.26+ and both has the same issue

**Comment by popcornmix** [comment]
Can you identify if it a firmware (start.elf) update or kernel (kernel.img) update that broke it?

Make a copy of start_.elf and fixup_.dat from a working image, and replace those files on latest / non-working image and see if it fixes the issue.

If it does it's a firmware issue. If not it's a kernel issue.

**Comment by pete111** [comment]
Hello, I am referring it is kernel issue.
I tried on model B firmware before/after update but problem persists so it is kernel related - so I tried kernels:
3.12.22+ AFFECTED
3.12.26+ AFFECTED
3.13.11 AFFECTED (I compiled Rpi 3.13 from git because it has slightly modified stk1160 driver than 3.12.x)
3.10.25+ WORKING OK.

So my question is. How can I compile 3.12.26+ with drivers from 3.10.25+? Or what should I do when I want to use driver from 3.10.25+ / or do you plan to incorporate it in new kernel?

**Comment by pete111** [comment]
the most recent findings and probably the most important - Now I am sure it is not driver related but what's the worst kernel related issue. I tried this - I compiled 3.10.28 kernel with the most recent (the newest) stk1160 driver and it is working amazing! 
So it must be something wrong in kernel version >= 3.12. 

Any idea what it could be and how to fix it?

**Comment by P33M** [comment]
The driver in question may have gone through a rewrite around the time that 3.10->3.12 happened.

http://www.linuxtv.org/wiki/index.php/Stk1160_based_USB_2.0_video_and_audio_capture_devices

Can you post the output of `lsmod` and `modinfo <the driver module>` in the 3.10 and 3.12 case?

**Comment by blamesoft** [comment]
I am also having this issue with my B+ and 3.12
STK1160 = /dev/video0 does not show up
Empia = /dev/video0 shows up, but the screenshots are black
USBTV007 = I have one on order, but I'm thinking it'll have the same results as the SKT1160

Lightberry.eu created a custom OpenELEC image, but it only supports the Fushicai USBTV007 grabber

EDIT:
I found this article about how to roll back to the 3.10 kernel. I'm going to try it now and see if it resolves the issue.
http://sourceforge.net/p/raspbmcusbtv/wiki/Installation/
2EDIT:
Didn't try it, rereading the article it specifically states that it only fixes the USBTV007. I'm not sure how hard it would be to replicate this for the STK1160, that is far above my skill level.

**Comment by Giraphe** [comment]
Hi,

Same problem here. I have a USBTV007 usb grabber from lightberry.eu.
I can compile the usbtv.ko but the rpi is crashing when i do the modprobe usbtv.

I have latest kernel 3.12.26+ for Raspbian

If I plug the same usb grabber in my other PC running Ubuntu and a 3.13 kernel everything works fine in plug and play mode and I can see /dev/video0 in filesystem.

Raphaël

**Comment by blamesoft** [comment]
Giraphe,

It looks like Lightberry just added a new OpenELEC image for the USBTV007 and the B+ board. I don't know if that will help you at all. http://img.lightberry.eu/download/OpenELEC-RPi.4.1.5_with_hyperion.zip

That of course will only help if you want to run it with OpenELEC, otherwise maybe the link I posed above will help? http://sourceforge.net/p/raspbmcusbtv/wiki/Installation/

**Comment by Giraphe** [comment]
Hi,

Thanks for the info however I'm not using OpenElec.
But I will try tonight the other link you provided as soon as I get back access to my rpi.
It doesn't like either to boot with the grabber connected.

Raphaël

**Comment by blamesoft** [comment]
For others,

They added STK1180 (and I think USBTV007 previously) in the latest beta build (4.2 Beta 6) of OpenELEC http://openelec.tv/news/22-releases/138-openelec-4-2-beta-6-released

<i>"This release includes some bugfixes, security fixes and improvements since OpenELEC-4.1.5. Besides the usual bugfixes and package updates we updated Mesa to Mesa-10.3-rc3, llvm to llvm-3.5.0 and kernel to linux 3.16.2. We fixed a crash in our installer and when pairing a PS3 remote and updated the RaspberryPi firmware to include the last fixes and features. <b>Also we added STK1160 frame grabber</b>, CH341 USB-serial support and the PSTATE CPU scaling driver for Intel Systems."</i>

I'm installing it and trying now.

I'm surprised more people are not having this issue? Doesn't Raspbmc update automatically by default? Wouldn't that have broken this for just about everyone? Or does just about everyone turn automatic updates off?

I'm also new to the Raspberry Pi and Linux in general, is there not a database somewhere that keeps old versions of Raspbmc and others like it around for purposes like this?

**Comment by Giraphe** [comment]
Hi,

So many thanks as with the replacement kernel it is working great.
I have the /dev/video0 and I was able to take screenshot and to see grabbed tv.

I still have other issues but you really helped me.

Many thanks !!

Raphaël

**Comment by Ruffio** [comment]
@pete111 has this issue been resolved? If yes, then please close this issue.

**Comment by P33M** [comment]
Closing USB issues as OP has not updated the thread. Further comments by the OP stating that the issue is still present on latest rpi-update kernel will lead to a review.
