### ISSUE TITLE
Maintain 3.14 branch as it is new LTS release

### ISSUE THREAD

**Issue by peerchemist** [raspberrypi/linux#720]
Just keeping point releases up to date would be enough from you guys, package maintainers can do the rest of work easily. Current point release is 3.14.23 and latest from 3.14.y branch here is .6.
Thanks.

**Comment by popcornmix** [comment]
We're contemplating moving on from 3.12.y for default kernel.
3.14.y is one option (due to LTS)
3.17.y is the other option (used by OpenELEC and seems to work well. More features and driver support).

LTS is obviously useful if there are no plans to move to newer kernels, but if you bump major kernel versions regularly, then LTS is of less importance.

Some things, like moving towards the upstream bcm2835 kernel platform will require moving to newer major kernel version.

**Comment by popcornmix** [comment]
I'll look into bumping 3.14 anyway, as minor releases can normally be upgraded easily. It won't be heavily tested though.

**Comment by peerchemist** [comment]
No need for heavy testing I guess, package maintainer (like me) can take care of that along the way.
Simple bump on point release once in the while is fine with me.

Thank you.

**Comment by peerchemist** [comment]
Please bump to .27, it was released today: http://lwn.net/Articles/626580/

**Comment by amtssp** [comment]
Do you think it is about time to go for 3.14 or 3.17 as default kernel for raspberry instead of 3.12 as you considered november 6? 

As far as I understood previously you had a stable version (currently 3.12) and a "next" kernel - but now there are several development kernels 3.14, 3.16, 3.17 and 3.18.
Why not continue with a stable kernel and one development kernel?

**Comment by popcornmix** [comment]
3.18 will be the next default kernel.
If you want to help with testing then try the BRANCH=next firmware and read here:
http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=93015

**Comment by peerchemist** [comment]
Please bump to .28

**Comment by popcornmix** [comment]
Okay, I've bumped it.

**Comment by peerchemist** [comment]
Much obliged.

**Comment by peerchemist** [comment]
Can you please bump to .36

**Comment by popcornmix** [comment]
3.18 is now LTS: https://www.kernel.org/

**Comment by peerchemist** [comment]
Missed that news. Ok I will close this if you have no intention to update 3.14 branch anymore.

**Comment by popcornmix** [comment]
If you want to continue with 3.14.y, then fork this repo and run:

```
git rebase -i --onto stable/linux-3.14.y stable/linux-3.14.y rpi-3.14.y
```

Or even better move to 3.18.y.
whenever upstream linux-3.14.y is bumped. I think there is no reason now for us to be maintaining an old kernel tree.

**Comment by Ruffio** [comment]
@popcornmix please close this issue, as we are way past 3.18
