### ISSUE TITLE
gcc compiler version

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/linux#741]
Apologies if this is not the right place to note this issue.

It is noted all over the place that modules compiled for Linux should use the same version of the compiler that is used to compile the kernel.

The latest 3.12.xx raspbian kernels are compiled with gcc 4.8. However the version of gcc included in the kernel images is 4.6, and that goes back a long way. Shouldn't the compilers be updated to version 4.8 to comply with the compiler version used for compiling the RPi kernels? Using gcc4.6 creates issues with wifi drivers I compile which are solved using gcc 4.7 or 4.8. Currently I manually update gcc etc. to ensure the issues don't appear.

**Comment by popcornmix** [comment]
This is a raspbian issue rather than a kernel issue.
Debian has chosen gcc 4.6 for wheezy, and that is so that is what raspbian uses.
I believe Debian uses gcc 4.9 for jessie, so if we update there, you would have a newer compiler by default.

The only other solution is to build the official kernel with gcc 4.6. However that is a much older compiler, and would likely lead to a slower kernel.

I think considering the number of people who use the kernel vs the number of people who build the kernel (i.e. > 10000:1) we're best off using what is best for the majority.

I imagine most people who build the kernel are cross-compiling, and the exact compiler is available in the tools repo.

It's not hard to install gcc-4.8 on raspbian:
http://somewideopenspace.wordpress.com/2014/02/28/gcc-4-8-on-raspberry-pi-wheezy/

**Comment by MrEngman** [comment]
Thanks. I have various versions of gcc installed and select the one that matches the version used to compile the kernel that I'm compiling modules for.

Just found it a bit odd that with the raspbian kernels compiled with gcc 4.8 the version of gcc included with the images is 4.6.
