### ISSUE TITLE
zram compressed ramdisk for swap

### ISSUE THREAD

**Issue by pssc** [raspberrypi/linux#894]
It makes checking out the kernel possible on my rev2 B pi and compilation somewhat quicker.
This has been requested before but wasn’t available as a module in 3.12 and had to be complied in.

CONFIG_ZSMALLOC=m
CONFIG_PGTABLE_MAPPING=y

CONFIG_ZRAM=m
CONFIG_ZRAM_LZ4_COMPRESS=y

CONFIG_LZ4_COMPRESS=m
CONFIG_LZ4_DECOMPRESS=m

**Comment by popcornmix** [comment]
Do you have any benchmarks showing the improvement?
(e.g. time to compile an app with and without compressed ramdisk?)

I'll look into it. Enabling as a module on 3.18 should be possible.

**Comment by pssc** [comment]
I only properly benchmarked to see if it was worth enabling  CONFIG_PGTABLE_MAPPING for this arch. it was a factor of ~two quicker.

**Comment by pssc** [comment]
my git pull for the kernel falls over with allocation error without the swap enabled , with this enabled I don't end up using up my SD card by swapping.

**Comment by jbruchon** [comment]
I am using Xbian and based on my experience, Xbian has some glitches and slowdowns because it swaps to and from the SD card occasionally. The swap is never more than about 105MB total. zram "I/O" performance is extremely high compared to even my Class 10 SD card. If I had access to the zram module, I'd be able to use it to eliminate my playback issues. There is no good reason to _not_ have the zram module available, especially since the Pi is the type of system that needs zram swap the most.

Regarding benchmarks, compilation performance is a poor benchmark because it is not a typical load for most users (if compilation performance matters, you are cross-compiling anyway) and hitting swap may not occur at all. A much better test would be running various tests using a web browser such as Firefox which often consumes all available RAM and gets OOM killed often if swap is disabled.

**Comment by popcornmix** [comment]
Should be enabled now. Can you rpi-update and test?

**Comment by jbruchon** [comment]
I don't personally have rpi-update (xbian doesn't appear to have it.) Any alternative ways to obtain and test?

**Comment by popcornmix** [comment]
@jbruchon You'll have to ask in xbian forums. I suspect they build their own kernel, so this change will have no effect (they can of course make a similar change themselves).

**Comment by pssc** [comment]
I have this ok and working on one of my rev 2 B's that's under heavy load.

**Comment by popcornmix** [comment]
Okay to close?

**Comment by PeterPablo** [comment]
I have also updated. Though not being able to give quantitative benchmark results, I have the impression that performance has improved (apache server, busy with owncloud). No problematic messages in `syslog` as far as I observed.

**Comment by yutayu** [comment]
https://github.com/armbian/build/pull/2377
https://github.com/armbian/build/pull/2377/commits/e90a488f24d4ba7f0947930f485c4e69a09e9374

CONFIG_PGTABLE_MAPPING=y
It seems it causes error.
Like this ,https://github.com/raspberrypi/linux/issues/3839.
