### ISSUE TITLE
Module required for chainloading boot to USB seems to be compiled only as a module

### ISSUE THREAD

**Issue by Hexxeh** [raspberrypi/linux#9]
I'm trying to chainload boot from the kernel on the SD card to a rootFS stored on a USB stick (for better read/write speeds, but also because my rootFS needs to be on a GPT-formatted disk).

It appears a module required to use a USB stick with the Pi is only compiled as a module: ./3.1.9+/kernel/drivers/usb/storage/uas.ko

Can this be changed in the default config, and therefore in the binaries provided in the firmware repo?

**Comment by asb** [comment]
This sounds like a reasonable request. I think we'd looked at including only the minimal required modules to boot...but then stretch that to include enough for e.g. nfsroot because that's handy. A similar argument applies here.

If you have time to test and let us know exactly what CONFIG_\* defines you need, that would be helpful.

**Comment by Hexxeh** [comment]
CONFIG_USB_STORAGE=y
CONFIG_USB_UAS=y
CONFIG_BLK_DEV_SD=y

Those three options seem to do the trick for me.

Getting roughly 3.5x the read speeds from a USB stick compared to what I got from a Class 4 SD card (and a crappy USB stick at that!)

**Comment by Hexxeh** [comment]
Looks like this has appeared in the latest binaries, thanks!
